//! Ordinary-dependency behavior against `cabin-ports/*` registry
//! packages, resolved from a hermetic file registry.
//!
//! The fixture registry is generated by the publisher's own
//! conversion pipeline (`cabin-port-publish`) from the *committed*
//! overlays, so these tests consume the same canonical packages the
//! hosted `cabin-ports` scope serves: scoped lowercase names,
//! native-artifact target keys (`zlib`'s sole library target
//! publishes as `z`), rewritten inter-port dependencies, and stamped
//! `[package.upstream]` provenance.
//! Every upstream archive is a fake seeded into the port cache under
//! an unreachable `https://` pin, so nothing here touches the
//! network.  Builtin-port (`port = true` / `port-path`) mechanics
//! keep their own coverage under `foundation_port_*`; this module
//! covers the registry consumption path those recipes publish into.

use super::*;

const FAKE_ZLIB_H: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/zlib/zlib.h");
const FAKE_ZLIB_C: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/zlib/zutil.c");
const ZLIB_OVERLAY: &str = include_str!("../../../cabin-port/ports/zlib/1.3.1/cabin.toml");
const ZLIB_MAIN_C: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/zlib/main.c");

const FAKE_TINYXML2_H: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/tinyxml2/tinyxml2.h");
const FAKE_TINYXML2_CPP: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/tinyxml2/tinyxml2.cpp");
const TINYXML2_OVERLAY: &str = include_str!("../../../cabin-port/ports/tinyxml2/11.0.0/cabin.toml");
const TINYXML2_MAIN_CPP: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/tinyxml2/main.cpp");

const FAKE_SQLITE3_H: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/sqlite3/sqlite3.h");
const FAKE_SQLITE3_C: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/sqlite3/sqlite3.c");
// sqlite3 is committed as a package, not a recipe, so its manifest
// no longer describes a recipe overlay; the fake port carries its own.
const SQLITE3_OVERLAY: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/sqlite3/cabin.toml");
const SQLITE3_MAIN_C: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-port-smoke/sqlite3/main.c");

const FAKE_PNG_H: &str = include_str!(
    "../../../cabin-port/tests/fixtures/fake-libpng-transitive/archives/fake-libpng-1.6.50/png.h"
);
const FAKE_PNG_C: &str = include_str!(
    "../../../cabin-port/tests/fixtures/fake-libpng-transitive/archives/fake-libpng-1.6.50/png.c"
);
const FAKE_PNGLIBCONF_H: &str = include_str!(
    "../../../cabin-port/tests/fixtures/fake-libpng-transitive/archives/fake-libpng-1.6.50/scripts/pnglibconf.h.prebuilt"
);
const LIBPNG_OVERLAY: &str = include_str!("../../../cabin-port/ports/libpng/1.6.50/cabin.toml");
const LIBPNG_MAIN_C: &str =
    include_str!("../../../cabin-port/tests/fixtures/fake-libpng-transitive/consumer/src/main.c");

const STB_OVERLAY: &str = include_str!("../../../cabin-port/ports/stb/2026.4.15/cabin.toml");
// The fake stb archive carries one single-file header in the
// upstream pattern (declaration-only unless the consumer TU defines
// the implementation macro), so the consumer proves both the
// header-only include propagation and the interface-standard floor.
const FAKE_STB_H: &str = "#ifndef FAKE_STB_ANSWER_H\n#define FAKE_STB_ANSWER_H\nint stb_answer(void);\n#ifdef STB_ANSWER_IMPLEMENTATION\nint stb_answer(void) { return 42; }\n#endif\n#endif\n";

// Only the multi-library scenario has no committed recipe shaped for
// it, so it alone uses a synthetic overlay.
const TOOLBOX_OVERLAY: &str = r#"[package]
name = "toolbox"
version = "1.2.3"

[target.alpha]
type = "library"
sources = ["alpha.c"]
include-dirs = ["."]
c-standard = "c11"

[target.beta]
type = "library"
sources = ["beta.c"]
include-dirs = ["."]
c-standard = "c11"
"#;

/// A staged fixture registry plus the cache its archives were seeded
/// into.  Consumers pass `--index-path registry()` and `--cache-dir
/// cache()` and are written under `root`.
struct StagedPorts {
    root: TempDir,
}

impl StagedPorts {
    fn registry(&self) -> PathBuf {
        self.root.path().join("stage/registry")
    }

    fn cache(&self) -> PathBuf {
        self.root.path().join("cache")
    }

    fn consumer_root(&self) -> &Path {
        self.root.path()
    }
}

/// Build the fixture recipe set from the committed overlays (fake
/// upstream sources under each recipe's real layout), convert it
/// with the publisher pipeline, and publish it into a file registry:
///
/// - `zlib` 1.3.1 - C library; the target key renames to the native
///   stem `z`;
/// - `libpng` 1.6.50 - depends on zlib (`{ port = true }` in the
///   committed overlay, rewritten to the scoped edge) and places
///   `pnglibconf.h` via the recipe's `[[copy]]` step;
/// - `tinyxml2` 11.0.0 - C++ library;
/// - `sqlite3` 3.53.2 - carries the `single-threaded` feature;
/// - `stb` 2026.4.15 - header-only;
/// - `toolbox` 1.2.3 - synthetic two-library package for the
///   explicit `package:target` selector scenario.
fn stage_fixture_ports() -> StagedPorts {
    let root = TempDir::new().unwrap();
    let cache = root.path().join("cache");
    let repo = FakePortRepo::new(root.path());

    let zlib = repo
        .port("zlib", "1.3.1")
        .archive_prefix("zlib-1.3.1")
        .file("zlib.h", FAKE_ZLIB_H)
        .stub_declared_sources_except(ZLIB_OVERLAY, "zlib", &["zutil.c"])
        .file("zutil.c", FAKE_ZLIB_C)
        .overlay_manifest(ZLIB_OVERLAY)
        .build();

    let libpng = repo
        .port("libpng", "1.6.50")
        .archive_prefix("libpng-1.6.50")
        .file("png.h", FAKE_PNG_H)
        .stub_declared_sources_except(LIBPNG_OVERLAY, "libpng", &["png.c"])
        .file("png.c", FAKE_PNG_C)
        .file("scripts/pnglibconf.h.prebuilt", FAKE_PNGLIBCONF_H)
        .copy("scripts/pnglibconf.h.prebuilt", "pnglibconf.h")
        .overlay_manifest(LIBPNG_OVERLAY)
        .build();

    let tinyxml2 = repo
        .port("tinyxml2", "11.0.0")
        .archive_prefix("tinyxml2-11.0.0")
        .file("tinyxml2.h", FAKE_TINYXML2_H)
        .file("tinyxml2.cpp", FAKE_TINYXML2_CPP)
        .overlay_manifest(TINYXML2_OVERLAY)
        .build();

    let sqlite3 = repo
        .port("sqlite3", "3.53.2")
        .archive_prefix("sqlite-autoconf-3530200")
        .file("sqlite3.h", FAKE_SQLITE3_H)
        .file("sqlite3.c", FAKE_SQLITE3_C)
        .overlay_manifest(SQLITE3_OVERLAY)
        .build();

    let stb = repo
        .port("stb", "2026.4.15")
        .archive_prefix("stb-2026.4.15")
        .file("stb_answer.h", FAKE_STB_H)
        .overlay_manifest(STB_OVERLAY)
        .build();

    let toolbox = repo
        .port("toolbox", "1.2.3")
        .archive_prefix("toolbox-1.2.3")
        .file(
            "alpha.h",
            "#ifndef FAKE_ALPHA_H\n#define FAKE_ALPHA_H\nint alpha_value(void);\n#endif\n",
        )
        .file(
            "alpha.c",
            "#include \"alpha.h\"\nint alpha_value(void) { return 40; }\n",
        )
        .file(
            "beta.h",
            "#ifndef FAKE_BETA_H\n#define FAKE_BETA_H\nint beta_value(void);\n#endif\n",
        )
        .file(
            "beta.c",
            "#include \"beta.h\"\nint beta_value(void) { return 2; }\n",
        )
        .overlay_manifest(TOOLBOX_OVERLAY)
        .build();

    for port in [&zlib, &libpng, &tinyxml2, &sqlite3, &stb, &toolbox] {
        port.pin_https_source_and_seed_cache(&cache);
    }

    stage_ports_registry(
        &root.path().join("ports"),
        &cache,
        &root.path().join("stage"),
    );
    StagedPorts { root }
}

fn build_and_run(staged: &StagedPorts, manifest: &Path, build_dir: &Path) -> String {
    cabin()
        .args(["build", "--manifest-path"])
        .arg(manifest)
        .arg("--index-path")
        .arg(staged.registry())
        .arg("--cache-dir")
        .arg(staged.cache())
        .arg("--build-dir")
        .arg(build_dir)
        .assert()
        .success();
    let output = cabin()
        .args(["run", "--manifest-path"])
        .arg(manifest)
        .arg("--index-path")
        .arg(staged.registry())
        .arg("--cache-dir")
        .arg(staged.cache())
        .arg("--build-dir")
        .arg(build_dir)
        .assert()
        .success()
        .get_output()
        .clone();
    String::from_utf8(output.stdout).expect("stdout is utf-8")
}

/// `deps = ["cabin-ports/zlib"]` resolves to the package's sole
/// library target even though it publishes under the native stem
/// `z`.
#[test]
fn bare_scoped_dep_builds_and_runs_against_renamed_target() {
    require_c_and_cxx_build_tools();
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "zlib-consumer",
        dependencies: r#""cabin-ports/zlib" = "=1.3.1""#,
        target_deps: &["cabin-ports/zlib"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: ZLIB_MAIN_C,
    }
    .write(staged.consumer_root());
    let build_dir = staged.consumer_root().join("build");

    let stdout = build_and_run(&staged, &manifest, &build_dir);
    assert!(stdout.contains("fake zlib: fake-zlib/1.3.1"), "{stdout}");

    // The target key decides the artifact stem: `libz.a` / `z.lib`,
    // not `libzlib.a`.
    let archive = build_dir
        .join("dev/packages/cabin-ports/zlib")
        .join(host_static_lib("z"));
    assert!(archive.is_file(), "missing {}", archive.display());
}

#[test]
fn cxx_library_package_builds_and_runs() {
    require_cxx_build_tools();
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "tinyxml2-consumer",
        dependencies: r#""cabin-ports/tinyxml2" = "=11.0.0""#,
        target_deps: &["cabin-ports/tinyxml2"],
        standard: r#"cxx-standard = "c++17""#,
        source_name: "main.cpp",
        source: TINYXML2_MAIN_CPP,
    }
    .write(staged.consumer_root());

    let stdout = build_and_run(&staged, &manifest, &staged.consumer_root().join("build"));
    assert!(stdout.contains("fake tinyxml2: 11.0.0"), "{stdout}");
}

/// A header-only package contributes no archive to the link; the
/// passing run proves its include dir propagated through the
/// registry dependency edge and the implementation-macro pattern
/// compiled in the consumer's own translation unit.
#[test]
fn header_only_package_builds_and_runs() {
    require_c_and_cxx_build_tools();
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "stb-consumer",
        dependencies: r#""cabin-ports/stb" = "=2026.4.15""#,
        target_deps: &["cabin-ports/stb"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "#include <stdio.h>\n#define STB_ANSWER_IMPLEMENTATION\n#include \"stb_answer.h\"\nint main(void) { printf(\"stb answer: %d\\n\", stb_answer()); return 0; }\n",
    }
    .write(staged.consumer_root());

    let stdout = build_and_run(&staged, &manifest, &staged.consumer_root().join("build"));
    assert!(stdout.contains("stb answer: 42"), "{stdout}");
}

/// The `single-threaded` feature flows through an ordinary registry
/// dependency edge exactly as it does through the port edge: SQLite
/// compiles with `SQLITE_THREADSAFE=0` and reports it at run time.
#[test]
fn feature_flows_through_registry_dependency_edge() {
    require_c_and_cxx_build_tools();
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "sqlite3-consumer",
        dependencies: r#""cabin-ports/sqlite3" = { version = "=3.53.2", features = ["single-threaded"] }"#,
        target_deps: &["cabin-ports/sqlite3"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: SQLITE3_MAIN_C,
    }
    .write(staged.consumer_root());

    let stdout = build_and_run(&staged, &manifest, &staged.consumer_root().join("build"));
    for expected in ["fake sqlite3: 3.53.2", "fake sqlite3 threadsafe: 0"] {
        assert!(stdout.contains(expected), "missing `{expected}`: {stdout}");
    }
}

/// The consumer declares only `cabin-ports/libpng`; zlib arrives
/// transitively through libpng's converted `"cabin-ports/zlib" =
/// "^1.3"` edge, the `[[copy]]`-placed `pnglibconf.h` is part of
/// the published package, and both published archives land on the
/// link.
#[test]
fn transitive_scoped_dep_builds_and_links_both_archives() {
    require_c_and_cxx_build_tools();
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "png-consumer",
        dependencies: r#""cabin-ports/libpng" = "=1.6.50""#,
        target_deps: &["cabin-ports/libpng"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: LIBPNG_MAIN_C,
    }
    .write(staged.consumer_root());
    let build_dir = staged.consumer_root().join("build");

    let stdout = build_and_run(&staged, &manifest, &build_dir);
    for expected in [
        "fake libpng version: 10650",
        "fake zlib via libpng: fake-zlib/1.3.1",
    ] {
        assert!(stdout.contains(expected), "missing `{expected}`: {stdout}");
    }

    for (package, stem) in [("libpng", "png"), ("zlib", "z")] {
        let archive = build_dir
            .join("dev/packages/cabin-ports")
            .join(package)
            .join(host_static_lib(stem));
        assert!(archive.is_file(), "missing {}", archive.display());
    }
}

/// `cabin resolve` records scoped registry dependencies in the
/// lockfile - the full scoped name, the plain upstream version,
/// `source = "index"`, and the index checksum (which pins the
/// packaging revision) - and a `--locked` re-resolve leaves the file
/// byte-identical.
#[test]
fn lockfile_round_trips_scoped_registry_dependencies() {
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "lock-consumer",
        dependencies: r#""cabin-ports/libpng" = "=1.6.50""#,
        target_deps: &[],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "int main(void) { return 0; }\n",
    }
    .write(staged.consumer_root());

    cabin()
        .args(["resolve", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(staged.registry())
        .assert()
        .success();

    let lockfile_path = manifest.parent().unwrap().join("cabin.lock");
    let lockfile = fs::read_to_string(&lockfile_path).unwrap();
    for expected in [
        "name = \"cabin-ports/libpng\"",
        "version = \"1.6.50\"",
        "name = \"cabin-ports/zlib\"",
        "version = \"1.3.1\"",
        "source = \"index\"",
        "checksum = \"sha256:",
    ] {
        assert!(
            lockfile.contains(expected),
            "missing `{expected}` in lockfile:\n{lockfile}"
        );
    }

    cabin()
        .args(["resolve", "--locked", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(staged.registry())
        .assert()
        .success();
    assert_eq!(
        lockfile,
        fs::read_to_string(&lockfile_path).unwrap(),
        "a --locked re-resolve must not rewrite the lockfile"
    );
}

/// `cabin fetch` populates the content-addressed cache from the
/// registry; once warm, the registry's artifact store is no longer
/// needed (`--offline`, and `--frozen`'s no-cache-writes mode both
/// succeed), while `--frozen` against a pristine cache fails with
/// the artifact-cache diagnostic.
#[test]
fn fetch_caches_registry_archives_for_offline_reuse() {
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "fetch-consumer",
        dependencies: r#""cabin-ports/zlib" = "=1.3.1""#,
        target_deps: &[],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "int main(void) { return 0; }\n",
    }
    .write(staged.consumer_root());

    let fetch = |cache: PathBuf, extra: &[&str]| {
        let mut cmd = cabin();
        cmd.args(["fetch", "--manifest-path"])
            .arg(&manifest)
            .arg("--index-path")
            .arg(staged.registry())
            .arg("--cache-dir")
            .arg(cache);
        cmd.args(extra);
        cmd
    };

    fetch(staged.cache(), &[]).assert().success();

    // The archive was extracted into the shared source cache.
    let sources = staged.cache().join("sources/sha256");
    let extracted = fs::read_dir(&sources)
        .unwrap()
        .filter_map(Result::ok)
        .any(|entry| entry.path().join("cabin.toml").is_file());
    assert!(extracted, "no extracted source under {}", sources.display());

    // With the cache warm, the registry's artifact store is dead
    // weight: park it, and offline / frozen re-fetches still succeed
    // from the cache.
    fs::rename(
        staged.registry().join("artifacts"),
        staged.root.path().join("artifacts-parked"),
    )
    .unwrap();
    fetch(staged.cache(), &["--offline"]).assert().success();
    fetch(staged.cache(), &["--frozen"]).assert().success();

    // A pristine cache under --frozen must fail (populating the
    // cache is forbidden) with the artifact-cache diagnostic.
    fetch(staged.root.path().join("cache-pristine"), &["--frozen"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("cabin-ports/zlib"))
        .stderr(predicate::str::contains(
            "--frozen was specified and the artifact is not cached",
        ));
}

/// `cabin vendor` materializes the scoped registry layout, and a
/// build against nothing but the vendor directory (fresh cache,
/// `--offline`) reconstructs the whole graph from it.
#[test]
fn vendor_reconstructs_offline_builds_from_scoped_registry() {
    require_c_and_cxx_build_tools();
    let staged = stage_fixture_ports();
    let manifest = RegistryConsumer {
        name: "vendor-consumer",
        dependencies: r#""cabin-ports/libpng" = "=1.6.50""#,
        target_deps: &["cabin-ports/libpng"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: LIBPNG_MAIN_C,
    }
    .write(staged.consumer_root());
    let vendor_dir = staged.consumer_root().join("vendor");

    cabin()
        .args(["vendor", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(staged.registry())
        .arg("--cache-dir")
        .arg(staged.cache())
        .arg("--vendor-dir")
        .arg(&vendor_dir)
        .assert()
        .success();

    // The vendor directory is itself a scoped file registry, its
    // artifact filenames revision-qualified.
    assert!(vendor_dir.join("packages/cabin-ports/zlib.json").is_file());
    assert!(
        vendor_dir
            .join("packages/cabin-ports/libpng.json")
            .is_file()
    );
    let vendored_revision = |package: &str, version: &str| -> String {
        let body =
            fs::read_to_string(vendor_dir.join(format!("packages/cabin-ports/{package}.json")))
                .unwrap();
        let value: serde_json::Value = serde_json::from_str(&body).unwrap();
        value["versions"][version]["revision"]
            .as_str()
            .unwrap()
            .to_owned()
    };
    let zlib_rev = vendored_revision("zlib", "1.3.1");
    let libpng_rev = vendored_revision("libpng", "1.6.50");
    assert!(
        vendor_dir
            .join(format!(
                "artifacts/cabin-ports/zlib/cabin-ports-zlib-1.3.1-{zlib_rev}.zip"
            ))
            .is_file()
    );
    assert!(
        vendor_dir
            .join(format!(
                "artifacts/cabin-ports/libpng/cabin-ports-libpng-1.6.50-{libpng_rev}.zip"
            ))
            .is_file()
    );

    // Fresh cache + --offline: everything must come from the vendor
    // dir alone.
    let build_dir = staged.consumer_root().join("build-vendored");
    let vendored_cache = staged.root.path().join("cache-vendored");
    cabin()
        .args(["build", "--offline", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(&vendor_dir)
        .arg("--cache-dir")
        .arg(&vendored_cache)
        .arg("--build-dir")
        .arg(&build_dir)
        .assert()
        .success();
    let output = cabin()
        .args(["run", "--offline", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(&vendor_dir)
        .arg("--cache-dir")
        .arg(&vendored_cache)
        .arg("--build-dir")
        .arg(&build_dir)
        .assert()
        .success()
        .get_output()
        .clone();
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("fake libpng version: 10650"), "{stdout}");
}

/// A package with two library targets rejects the bare shorthand
/// with a diagnostic that demands `package:target`, and the explicit
/// selectors link both archives.
#[test]
fn explicit_target_selectors_link_a_multi_library_package() {
    require_c_and_cxx_build_tools();
    let staged = stage_fixture_ports();

    let ambiguous = RegistryConsumer {
        name: "toolbox-ambiguous",
        dependencies: r#""cabin-ports/toolbox" = "=1.2.3""#,
        target_deps: &["cabin-ports/toolbox"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "int main(void) { return 0; }\n",
    }
    .write(staged.consumer_root());
    cabin()
        .args(["build", "--manifest-path"])
        .arg(&ambiguous)
        .arg("--index-path")
        .arg(staged.registry())
        .arg("--cache-dir")
        .arg(staged.cache())
        .arg("--build-dir")
        .arg(staged.consumer_root().join("build-ambiguous"))
        .assert()
        .failure()
        .stderr(predicate::str::contains("cabin-ports/toolbox"))
        .stderr(predicate::str::contains("package:target"));

    let manifest = RegistryConsumer {
        name: "toolbox-consumer",
        dependencies: r#""cabin-ports/toolbox" = "=1.2.3""#,
        target_deps: &["cabin-ports/toolbox:alpha", "cabin-ports/toolbox:beta"],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "#include <stdio.h>\n#include \"alpha.h\"\n#include \"beta.h\"\nint main(void) { printf(\"toolbox sum: %d\\n\", alpha_value() + beta_value()); return 0; }\n",
    }
    .write(staged.consumer_root());
    let stdout = build_and_run(
        &staged,
        &manifest,
        &staged.consumer_root().join("build-toolbox"),
    );
    assert!(stdout.contains("toolbox sum: 42"), "{stdout}");
}

/// The recipe's pinned `[source]` round-trips end to end: the
/// conversion stamps `[package.upstream]`, the file registry's index
/// entry carries the same pin (URL, SHA-256, format, strip-prefix,
/// and the `[[copy]]` plan), and the archived manifest inside the
/// fetched package still declares it.
#[test]
fn patched_port_round_trips_through_the_staged_registry() {
    // Publisher round trip for a patch-carrying recipe: the staged
    // registry package ships the patched sources plus the patch file,
    // and its index entry and archived manifest both declare it.
    let root = TempDir::new().unwrap();
    let cache = root.path().join("cache");
    let repo = FakePortRepo::new(root.path());
    let patch = "--- a/zutil.c\n\
                 +++ b/zutil.c\n\
                 @@ -1,1 +1,1 @@\n\
                 -int fake_zlib_marker(void) { return 1; }\n\
                 +int fake_zlib_marker(void) { return 2; }\n";
    let zlib = repo
        .port("zlib", "1.3.1")
        .archive_prefix("zlib-1.3.1")
        .file("zlib.h", FAKE_ZLIB_H)
        .stub_declared_sources_except(ZLIB_OVERLAY, "zlib", &["zutil.c"])
        .file("zutil.c", "int fake_zlib_marker(void) { return 1; }\n")
        .patch("0001-fix.patch", patch)
        .overlay_manifest(ZLIB_OVERLAY)
        .build();
    zlib.pin_https_source_and_seed_cache(&cache);
    let registry = stage_ports_registry(
        &root.path().join("ports"),
        &cache,
        &root.path().join("stage"),
    );

    let index: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(registry.join("packages/cabin-ports/zlib.json")).unwrap(),
    )
    .unwrap();
    assert_eq!(
        index["versions"]["1.3.1"]["upstream"]["patches"],
        serde_json::json!(["patches/0001-fix.patch"])
    );

    let manifest = RegistryConsumer {
        name: "patched-consumer",
        dependencies: r#""cabin-ports/zlib" = "=1.3.1""#,
        target_deps: &[],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "int main(void) { return 0; }\n",
    }
    .write(root.path());
    cabin()
        .args(["fetch", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(&registry)
        .arg("--cache-dir")
        .arg(&cache)
        .assert()
        .success();

    let sources = cache.join("sources/sha256");
    let fetched = fs::read_dir(&sources)
        .unwrap()
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .find(|path| {
            fs::read_to_string(path.join("cabin.toml"))
                .is_ok_and(|manifest| manifest.contains("name = \"cabin-ports/zlib\""))
        })
        .expect("fetched zlib source tree");
    // The published tree carries the *patched* source and the patch
    // file itself at its declared path.
    assert_eq!(
        fs::read_to_string(fetched.join("zutil.c")).unwrap(),
        "int fake_zlib_marker(void) { return 2; }\n"
    );
    assert_eq!(
        fs::read_to_string(fetched.join("patches/0001-fix.patch")).unwrap(),
        patch
    );
    let archived_manifest = fs::read_to_string(fetched.join("cabin.toml")).unwrap();
    assert!(
        archived_manifest.contains("patches = [\"patches/0001-fix.patch\"]"),
        "archived manifest lacks the patch declaration:\n{archived_manifest}"
    );
}

#[test]
fn provenance_round_trips_recipe_pin_into_index_and_archived_manifest() {
    let staged = stage_fixture_ports();

    // Re-read the pin straight from the fixture recipe so the
    // assertion cannot drift from what was staged.
    let recipe =
        fs::read_to_string(staged.root.path().join("ports/libpng/1.6.50/port.toml")).unwrap();
    let pinned_sha = recipe
        .lines()
        .find_map(|line| line.strip_prefix("sha256 = \""))
        .and_then(|rest| rest.strip_suffix('"'))
        .expect("fixture recipe pins a sha256");

    let index: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(staged.registry().join("packages/cabin-ports/libpng.json")).unwrap(),
    )
    .unwrap();
    let upstream = &index["versions"]["1.6.50"]["upstream"];
    assert_eq!(
        upstream["url"],
        "https://ports.invalid/libpng-1.6.50.tar.gz"
    );
    assert_eq!(upstream["sha256"], pinned_sha);
    assert_eq!(upstream["format"], "tar.gz");
    assert_eq!(upstream["strip-prefix"], "libpng-1.6.50");
    assert_eq!(
        upstream["copy"],
        serde_json::json!([{ "from": "scripts/pnglibconf.h.prebuilt", "to": "pnglibconf.h" }])
    );

    // The libpng entry's dependency map carries the rewritten scoped
    // edge, so transitive resolution needs no port knowledge.
    assert_eq!(
        index["versions"]["1.6.50"]["dependencies"]["cabin-ports/zlib"],
        "^1.3"
    );

    // Fetch and inspect the archived manifest: the provenance table
    // is part of the published package, not just the index.
    let manifest = RegistryConsumer {
        name: "provenance-consumer",
        dependencies: r#""cabin-ports/libpng" = "=1.6.50""#,
        target_deps: &[],
        standard: r#"c-standard = "c11""#,
        source_name: "main.c",
        source: "int main(void) { return 0; }\n",
    }
    .write(staged.consumer_root());
    cabin()
        .args(["fetch", "--manifest-path"])
        .arg(&manifest)
        .arg("--index-path")
        .arg(staged.registry())
        .arg("--cache-dir")
        .arg(staged.cache())
        .assert()
        .success();

    let sources = staged.cache().join("sources/sha256");
    let archived_manifest = fs::read_dir(&sources)
        .unwrap()
        .filter_map(Result::ok)
        .filter_map(|entry| fs::read_to_string(entry.path().join("cabin.toml")).ok())
        .find(|manifest| manifest.contains("name = \"cabin-ports/libpng\""))
        .expect("fetched libpng source holds its archived manifest");
    for expected in [
        "[package.upstream]",
        "url = \"https://ports.invalid/libpng-1.6.50.tar.gz\"",
        "[[package.upstream.copy]]",
        "from = \"scripts/pnglibconf.h.prebuilt\"",
        "\"cabin-ports/zlib\" = \"^1.3\"",
        "[target.png]",
    ] {
        assert!(
            archived_manifest.contains(expected),
            "missing `{expected}` in archived manifest:\n{archived_manifest}"
        );
    }
}
