use std::fmt::Write as _;
use std::path::Path;

use cabin_build::{Action, ActionKind, BuildGraph};

use crate::error::NinjaError;

/// Write a `build.ninja` describing `graph` to `path`.
pub fn write_build_ninja(path: &Path, graph: &BuildGraph) -> Result<(), NinjaError> {
    let body = render_build_ninja(graph)?;
    std::fs::write(path, body).map_err(|source| NinjaError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(())
}

/// Render `graph` as a Ninja build file.
///
/// Pulled out so unit tests can exercise the formatter without touching the
/// filesystem.
pub fn render_build_ninja(graph: &BuildGraph) -> Result<String, NinjaError> {
    let mut out = String::new();
    out.push_str("# Generated by cabin. Do not edit by hand.\n");
    out.push_str("ninja_required_version = 1.10\n\n");

    out.push_str("rule c_compile\n");
    out.push_str("  command = $command\n");
    out.push_str("  depfile = $depfile\n");
    out.push_str("  deps = gcc\n");
    out.push_str("  description = $description\n\n");

    out.push_str("rule cxx_compile\n");
    out.push_str("  command = $command\n");
    out.push_str("  depfile = $depfile\n");
    out.push_str("  deps = gcc\n");
    out.push_str("  description = $description\n\n");

    out.push_str("rule cxx_archive\n");
    out.push_str("  command = $command\n");
    out.push_str("  description = $description\n\n");

    out.push_str("rule link_executable\n");
    out.push_str("  command = $command\n");
    out.push_str("  description = $description\n\n");

    for action in &graph.actions {
        write_edge(&mut out, action)?;
    }

    if !graph.default_outputs.is_empty() {
        out.push_str("default");
        for output in &graph.default_outputs {
            out.push(' ');
            out.push_str(&escape_path(path_to_str(output)?)?);
        }
        out.push('\n');
    }

    Ok(out)
}

fn write_edge(out: &mut String, action: &Action) -> Result<(), NinjaError> {
    let rule = match action.kind {
        ActionKind::CompileC => "c_compile",
        ActionKind::CompileCpp => "cxx_compile",
        ActionKind::ArchiveStaticLibrary => "cxx_archive",
        ActionKind::LinkExecutable => "link_executable",
    };

    out.push_str("build ");
    let mut first = true;
    for output in &action.outputs {
        if !first {
            out.push(' ');
        }
        first = false;
        out.push_str(&escape_path(path_to_str(output)?)?);
    }
    out.push_str(": ");
    out.push_str(rule);
    for input in &action.inputs {
        out.push(' ');
        out.push_str(&escape_path(path_to_str(input)?)?);
    }
    if !action.implicit_inputs.is_empty() {
        out.push_str(" |");
        for input in &action.implicit_inputs {
            out.push(' ');
            out.push_str(&escape_path(path_to_str(input)?)?);
        }
    }
    out.push('\n');

    let command_value = shell_join(&action.command);
    write_var(out, "command", &command_value)?;
    if let Some(depfile) = &action.depfile {
        write_var(out, "depfile", path_to_str(depfile)?)?;
    }
    write_var(out, "description", &action.description)?;
    out.push('\n');

    Ok(())
}

fn write_var(out: &mut String, key: &str, value: &str) -> Result<(), NinjaError> {
    // Ninja indents variable definitions inside a build edge with two
    // spaces. Within a value, `$` is meaningful (variable references
    // and line continuation) and a literal newline ends the value;
    // `escape_value` doubles `$` and rejects newlines so a manifest
    // string cannot inject a fresh statement.
    let _ = writeln!(out, "  {key} = {}", escape_value(value)?);
    Ok(())
}

fn path_to_str(p: &Path) -> Result<&str, NinjaError> {
    p.to_str()
        .ok_or_else(|| NinjaError::NonUtf8Path(p.to_path_buf()))
}

/// Escape a path for use as a token inside a Ninja `build` edge.
///
/// In token positions, Ninja recognises `$$` for a literal `$`, `$ ` for a
/// literal space, and `$:` for a literal colon. A literal newline cannot be
/// represented and is rejected.
pub(crate) fn escape_path(s: &str) -> Result<String, NinjaError> {
    if s.contains('\n') {
        return Err(NinjaError::PathHasNewline(s.into()));
    }
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            ' ' => out.push_str("$ "),
            ':' => out.push_str("$:"),
            '$' => out.push_str("$$"),
            other => out.push(other),
        }
    }
    Ok(out)
}

/// Escape a value for the right-hand side of a Ninja variable assignment.
///
/// In value positions `$` is special (used for variable references and
/// line continuation). Spaces are preserved verbatim. A literal `\n` or
/// `\r` would terminate the variable line and is rejected so a
/// manifest-derived value cannot inject sibling Ninja declarations.
pub(crate) fn escape_value(s: &str) -> Result<String, NinjaError> {
    if s.contains('\n') || s.contains('\r') {
        return Err(NinjaError::ValueHasNewline(s.to_owned()));
    }
    Ok(s.replace('$', "$$"))
}

/// Join an argv-style command into a single shell command line.
pub(crate) fn shell_join(args: &[String]) -> String {
    let mut out = String::new();
    for (index, arg) in args.iter().enumerate() {
        if index > 0 {
            out.push(' ');
        }
        out.push_str(&posix_shell_quote(arg));
    }
    out
}

/// POSIX-style shell quoting. Args containing only "safe" characters are
/// emitted verbatim; everything else is single-quoted.
fn posix_shell_quote(arg: &str) -> String {
    if arg.is_empty() {
        return "''".to_owned();
    }
    let safe = arg
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | '/' | '=' | '+' | ','));
    if safe {
        return arg.to_owned();
    }
    let mut out = String::with_capacity(arg.len() + 2);
    out.push('\'');
    for c in arg.chars() {
        if c == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(c);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use cabin_build::{ActionKind, BuildGraph, CompileCommand};
    use std::path::PathBuf;

    fn compile_action() -> Action {
        Action {
            kind: ActionKind::CompileCpp,
            inputs: vec![PathBuf::from("/abs/src/main.cc")],
            implicit_inputs: vec![],
            outputs: vec![PathBuf::from("/abs/build/main.o")],
            depfile: Some(PathBuf::from("/abs/build/main.o.d")),
            command: vec![
                "/usr/bin/g++".into(),
                "-std=c++17".into(),
                "-c".into(),
                "/abs/src/main.cc".into(),
                "-o".into(),
                "/abs/build/main.o".into(),
            ],
            description: "CXX /abs/build/main.o".into(),
        }
    }

    fn archive_action() -> Action {
        Action {
            kind: ActionKind::ArchiveStaticLibrary,
            inputs: vec![PathBuf::from("/abs/build/main.o")],
            implicit_inputs: vec![],
            outputs: vec![PathBuf::from("/abs/build/libfoo.a")],
            depfile: None,
            command: vec![
                "/usr/bin/ar".into(),
                "crs".into(),
                "/abs/build/libfoo.a".into(),
                "/abs/build/main.o".into(),
            ],
            description: "AR /abs/build/libfoo.a".into(),
        }
    }

    fn link_action() -> Action {
        Action {
            kind: ActionKind::LinkExecutable,
            inputs: vec![PathBuf::from("/abs/build/main.o")],
            implicit_inputs: vec![],
            outputs: vec![PathBuf::from("/abs/build/hello")],
            depfile: None,
            command: vec![
                "/usr/bin/g++".into(),
                "/abs/build/main.o".into(),
                "-o".into(),
                "/abs/build/hello".into(),
            ],
            description: "LINK /abs/build/hello".into(),
        }
    }

    fn graph_with(actions: Vec<Action>, defaults: Vec<PathBuf>) -> BuildGraph {
        BuildGraph {
            actions,
            default_outputs: defaults,
            compile_commands: Vec::<CompileCommand>::new(),
        }
    }

    #[test]
    fn renders_all_three_rule_kinds() {
        let body = render_build_ninja(&graph_with(
            vec![compile_action(), archive_action(), link_action()],
            vec![PathBuf::from("/abs/build/hello")],
        ))
        .unwrap();
        // Two compile rules — one per language — plus archive
        // and the language-neutral link rule. The link rule name
        // does not encode a language because the link driver is
        // selected per target by the planner and threaded into
        // the action's command, not into the rule name.
        assert!(body.contains("rule c_compile"));
        assert!(body.contains("rule cxx_compile"));
        assert!(body.contains("rule cxx_archive"));
        assert!(body.contains("rule link_executable"));
    }

    #[test]
    fn includes_default_targets() {
        let body = render_build_ninja(&graph_with(
            vec![compile_action()],
            vec![PathBuf::from("/abs/build/main.o")],
        ))
        .unwrap();
        assert!(body.contains("default /abs/build/main.o"));
    }

    #[test]
    fn compile_edge_carries_depfile() {
        let body = render_build_ninja(&graph_with(vec![compile_action()], vec![])).unwrap();
        assert!(body.contains("build /abs/build/main.o: cxx_compile /abs/src/main.cc"));
        assert!(body.contains("depfile = /abs/build/main.o.d"));
        assert!(body.contains("deps = gcc"));
    }

    #[test]
    fn link_edge_uses_link_rule() {
        let body = render_build_ninja(&graph_with(vec![link_action()], vec![])).unwrap();
        assert!(body.contains("build /abs/build/hello: link_executable /abs/build/main.o"));
    }

    #[test]
    fn archive_edge_uses_archive_rule() {
        let body = render_build_ninja(&graph_with(vec![archive_action()], vec![])).unwrap();
        assert!(body.contains("build /abs/build/libfoo.a: cxx_archive /abs/build/main.o"));
    }

    #[test]
    fn implicit_inputs_render_with_pipe() {
        let mut act = compile_action();
        act.implicit_inputs = vec![PathBuf::from("/abs/build/generated.h")];
        let body = render_build_ninja(&graph_with(vec![act], vec![])).unwrap();
        assert!(body.contains("| /abs/build/generated.h"));
    }

    #[test]
    fn escape_path_handles_specials() {
        assert_eq!(escape_path("simple/path").unwrap(), "simple/path");
        assert_eq!(escape_path("with space").unwrap(), "with$ space");
        assert_eq!(escape_path("with$dollar").unwrap(), "with$$dollar");
        assert_eq!(escape_path("foo:bar").unwrap(), "foo$:bar");
        assert!(escape_path("with\nnewline").is_err());
    }

    #[test]
    fn escape_value_only_doubles_dollars() {
        assert_eq!(escape_value("hello world").unwrap(), "hello world");
        assert_eq!(escape_value("$VAR").unwrap(), "$$VAR");
    }

    #[test]
    fn escape_value_rejects_newlines_and_carriage_returns() {
        // A literal newline or CR inside a value would terminate the
        // Ninja variable line and let the next-line content be
        // re-interpreted as a fresh top-level declaration. Reject so
        // a manifest-controlled string cannot smuggle in `rule` or
        // `command` overrides.
        assert!(matches!(
            escape_value("foo\nbar"),
            Err(NinjaError::ValueHasNewline(_))
        ));
        assert!(matches!(
            escape_value("foo\rbar"),
            Err(NinjaError::ValueHasNewline(_))
        ));
    }

    #[test]
    fn newline_in_description_aborts_render() {
        let mut act = compile_action();
        act.description = "CXX foo.o\n  rule injected".into();
        let err = render_build_ninja(&graph_with(vec![act], vec![])).unwrap_err();
        assert!(
            matches!(err, NinjaError::ValueHasNewline(_)),
            "expected ValueHasNewline, got {err:?}"
        );
    }

    #[test]
    fn newline_in_command_aborts_render() {
        let mut act = compile_action();
        act.command.push("payload\n  command = /bin/rm".into());
        let err = render_build_ninja(&graph_with(vec![act], vec![])).unwrap_err();
        assert!(
            matches!(err, NinjaError::ValueHasNewline(_)),
            "expected ValueHasNewline, got {err:?}"
        );
    }

    #[test]
    fn shell_quote_passes_safe_args_through() {
        assert_eq!(posix_shell_quote("simple"), "simple");
        assert_eq!(posix_shell_quote("/abs/path/foo.cc"), "/abs/path/foo.cc");
        assert_eq!(posix_shell_quote("-DFOO=BAR"), "-DFOO=BAR");
    }

    #[test]
    fn shell_quote_quotes_unsafe_args() {
        assert_eq!(posix_shell_quote("with space"), "'with space'");
        assert_eq!(posix_shell_quote(""), "''");
    }

    #[test]
    fn shell_quote_escapes_single_quote() {
        assert_eq!(posix_shell_quote("it's"), r"'it'\''s'");
    }

    #[test]
    fn render_includes_full_command_in_value() {
        let body = render_build_ninja(&graph_with(vec![compile_action()], vec![])).unwrap();
        // `command = ` line for the edge should contain the full shell command.
        assert!(body.contains(
            "command = /usr/bin/g++ -std=c++17 -c /abs/src/main.cc -o /abs/build/main.o"
        ));
    }
}
