# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      cargo:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/registry/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      cargo-registry:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/.github/commitlint/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      npm-commitlint:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/website/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 50
    groups:
      npm:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"
