[package]
name = "inih-usage"
version = "0.1.0"
c-standard = "c11"

[dependencies]
"cabin-ports/inih" = "=62.0.0"

[target.inih-usage]
type = "executable"
sources = ["src/main.c"]
deps = ["cabin-ports/inih"]
