language: cpp
rvm: system

before_cache:
  - brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - libyaml-cpp-dev
      - libboost-all-dev
      - libssl-dev
  coverity_scan:
    project:
      name: poacpm/poac
      description: Package manager for C++
    build_command_prepend: mkdir build && cd build
    build_command: cmake .. && make
    branch_pattern: coverity_scan

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      if: branch = coverity_scan
    # macOS Sierra
    - os: osx
      osx_image: xcode9.2
      if: branch != coverity_scan
    # macOS High Sierra
    - os: osx
      osx_image: xcode10.1
      if: branch != coverity_scan
    # macOS Mojave
    - os: osx
      osx_image: xcode10.2
      if: branch != coverity_scan

before_install:
  - brew update
install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$TRAVIS_OSX_IMAGE" != "xcode10.2" ]]; then
        brew unlink boost
        brew install --ignore-dependencies boost
        brew install llvm@7
      else
        pip install cpp-coveralls
      fi
      brew install yaml-cpp
    fi
script:
  - mkdir build
  - cd build
  - cmake ..
  - make install
  - poac -h
  - cd ../
after_success:
  - |
    if [[ "$TRAVIS_OSX_IMAGE" == "xcode10.2" ]]; then
      bash ./test.sh
    fi

notifications:
  email: false
  slack:
    secure: "UQ2hUnwff1tpHrsoZK4lI+hIrH8SIIL++0rIK+zXSInw6BVo8XMVqZ9VHoZffb3pchqO8snHsAv6DE6L3BC4N74SrDMK0PGC87sdg5iZlH11qDaIxQRImEGBOysJH8taZsjq+AcBZahtpuXrahB9seCBFvb4nOvS4OzVpcLHSUtyfNm3ACuL9JgJbXFv6zyD5AiXslqfsNCQqxBmklY/TjEIM2Wtt3g8zvEUqgH0ZA/fyao4wiihgAJ2BY6vvuXU1edNybtHNeJfuxnY87Mo8+xod/4/lfL48wjnaZ1muycSqPi2II78QEm3eyMWPJIvims2MIkaOwaBUtBSYsxBL1XuuUsbP2jRDprY35DAbsDKtbPLn6YuFEAFumsNCbiiF5XSorgDqGvTSoXpPX2dtO/xSbJf3NEs4i2z9MyiZCpWPyQV0q00rubB4PSJK6o7HmuHEjN89a8gSOJLWQO2e0ah9zL0crrxezVxUn/d9AB2mwTP9YSoUwjuercN7KSf0ZBzfYEMnpkKTe1aK1kpqcGtYHa8sHrwGypNvBsaVphXhaisYYnPSIMsnDasbU0Q66x3LtCvkA7zvQrFlessVpszcYEAQ9XYvVb2e18hVGWpkrCVjkAHCuzMZ/JAV/T+cK/WMxbRx/JIvyMkMGemlREqGMYnvNpGkY1uwF/pqYM="
