version: 1.0.{build}

branches:
  except:
    - gh-pages

configuration:
  - Debug
  - Release

platform: x64

clone_depth: 1

environment:
  matrix:
    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
    - COMPILER: cygwin64

install:
  - git clone https://github.com/jbeder/yaml-cpp.git

  - if [%COMPILER%]==[cygwin64] (
      C:\cygwin64\setup-x86_64.exe -qgnNdO --root C:\cygwin64 -s http://cygwin.mirror.constant.com -P make -P openssl-devel &&
      C:\cygwin64\bin\bash -l -c "cd yaml-cpp && mkdir build && cd build && cmake .. && make && cd ../.."
    )

  - if [%COMPILER%]==[mingw-w64] (
      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe" &&
      set PATH=C:\msys64\usr\bin;%PATH% &&
      pacman -Syu --noconfirm &&
      pacman -Syyu python --noconfirm mingw-w64-x86_64-gcc &&
      rename "C:\msys64\usr\bin\sh.exe" "sh2.exe" &&
      cd yaml-cpp && mkdir build && cd build &&
      cmake .. -G "%GENERATOR%" -DCMAKE_PREFIX_PATH=C:\mingw64 -DCMAKE_BUILD_TYPE=%Configuration% -DYAML_CPP_BUILD_TESTS=OFF -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_INSTALL_PREFIX=C:\Libraries\ &&
      cmake --build . --target install &&
      cd ..\..
    )

before_build:
  - if [%COMPILER%]==[mingw-w64] (
      mkdir build && cd build &&
      cmake .. -G "%GENERATOR%" -DBOOST_ROOT=C:\Libraries\boost_1_67_0 &&
      cmake --build . --config %Configuration% &&
      cd ..
    )
  - if [%COMPILER%]==[cygwin64] (
      C:\cygwin64\bin\bash -l -c "mkdir build && cd build && cmake .. -DCMAKE_CXX_FLAGS='-D_GNU_SOURCE -DBOOST_ASIO_HAS_STD_STRING_VIEW -Wa,-mbig-obj' && make" &&
    )

build:
  parallel: true
  verbosity: minimal

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 8Th9f6eSvN/wTVU6h5w9WZGmiKS+uHsl11nHGbR87OKy6/95p6rxiRuzHrJy7MXhanRW4+UqhR1r6C4wqIVDmzJgpRH4iW10mbc2by5sWWo=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
