version: 1.0.{build}

branches:
  except:
    - gh-pages

image:
  - Visual Studio 2017

#cache:
#  - C:\Libraries\yaml-cpp -> appveyor.yml

configuration:
  - Debug
  - Release

platform: x64

clone_depth: 1

environment:
  matrix:
    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
#    - COMPILER: mingw-w64
#      GENERATOR: MinGW Makefiles

install:
  - git clone https://github.com/jbeder/yaml-cpp.git

  - if [%COMPILER%]==[msvc] (
      cd yaml-cpp &&
      mkdir build &&
      cd build &&
      cmake .. -G "%GENERATOR%" ^
        -DYAML_CPP_BUILD_TESTS=OFF ^
        -DCMAKE_INSTALL_PREFIX=C:\Libraries\yaml-cpp &&
      cmake --build . --target install &&
      cd ..\..
    )

  - if [%COMPILER%]==[cygwin64] (
      xcopy /i /q /s C:\projects\poac\yaml-cpp C:\cygwin64\home\appveyor\yaml-cpp &&
      C:\cygwin64\setup-x86_64.exe -qgnNdO ^
        --root C:\cygwin64 ^
        -s http://cygwin.mirror.constant.com ^
        -P make -P openssl-devel &&
      mkdir C:\Libraries\yaml-cpp &&
      C:\cygwin64\bin\bash -l -c "cd yaml-cpp && mkdir build && cd build && cmake .. -G '%GENERATOR%' -DYAML_CPP_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/Libraries/yaml-cpp && cmake --build . --target install"
    )

  - if [%COMPILER%]==[mingw-w64] set PATH=C:\msys64\usr\bin;%PATH%
  - if [%COMPILER%]==[mingw-w64] (
      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe" &&
      pacman -Syu --noconfirm &&
      pacman -Syyu python --noconfirm mingw-w64-x86_64-gcc &&
      rename "C:\msys64\usr\bin\sh.exe" "sh2.exe" &&
      cd yaml-cpp && mkdir build && cd build &&
      cmake .. -G "%GENERATOR%" ^
        -DCMAKE_PREFIX_PATH=C:\mingw64 ^
        -DCMAKE_BUILD_TYPE=%Configuration% ^
        -DYAML_CPP_BUILD_TESTS=OFF ^
        -DCMAKE_SH=CMAKE_SH-NOTFOUND ^
        -DCMAKE_INSTALL_PREFIX=C:\Libraries\ &&
      cmake --build . --target install &&
      cd ..\..
    )

before_build:
  - if [%COMPILER%]==[msvc] (
      dir C:\Libraries\boost_1_69_0 &&
      mkdir build &&
      cd build &&
      cmake .. -G "%GENERATOR%" ^
        -DCMAKE_BUILD_TYPE=%Configuration% ^
        -DBOOST_ROOT=C:\Libraries\boost_1_69_0 &&
      cmake --build . &&
      cd ..
    )

  - if [%COMPILER%]==[cygwin64] (
      dir C:\Libraries\boost_1_69_0\boost &&
      xcopy /i /q /s C:\projects\poac C:\cygwin64\home\appveyor\poac &&
      C:\cygwin64\bin\bash -l -c "cd poac && mkdir build && cd build && cmake .. -G '%GENERATOR%' -DBOOST_ROOT=C:/Libraries/boost_1_69_0 && cmake --build ."
    )

  - if [%COMPILER%]==[mingw-w64] (
      mkdir build && cd build &&
      cmake .. -G "%GENERATOR%" -DBOOST_ROOT=C:\Libraries\boost_1_69_0 &&
      cmake --build . --config %Configuration% &&
      cd ..
    )

build:
  parallel: true
  verbosity: minimal

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 8Th9f6eSvN/wTVU6h5w9WZGmiKS+uHsl11nHGbR87OKy6/95p6rxiRuzHrJy7MXhanRW4+UqhR1r6C4wqIVDmzJgpRH4iW10mbc2by5sWWo=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
