site_name: Cabin Docs
theme: readthedocs
repo_url: https://github.com/cabinpkg/cabin
edit_uri: edit/main/docs/

nav:
  - index.md
  - why-cabin.md
  - installation.md
  - hello-world.md
  - usage.md
  - package-layout.md
  - acknowledgements.md
