//! Build script: generate the `BUILTIN` foundation-port table by
//! scanning the repository's `ports/` directory at compile time.
//!
//! Every `ports/<name>/<version>/` directory that contains both a
//! `port.toml` and an overlay `cabin.toml` is embedded automatically,
//! so adding a recipe directory is enough to bundle it — no manual
//! edits to `src/builtin.rs` are required. The generated table is
//! written to `$OUT_DIR/builtin_generated.rs` and `include!`d by
//! `src/builtin.rs`.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // crates/cabin-port -> repo root -> ports/
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ports_dir = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("cabin-port crate must live two levels below the repo root")
        .join("ports");

    // Rerun whenever anything under ports/ changes: a new or removed
    // recipe directory, or edited port.toml / cabin.toml contents.
    println!("cargo:rerun-if-changed={}", ports_dir.display());

    let mut entries = Vec::new();
    for name_dir in child_dirs(&ports_dir) {
        let name = file_name(&name_dir);
        for version_dir in child_dirs(&name_dir) {
            let version = file_name(&version_dir);
            let port_toml = version_dir.join("port.toml");
            let overlay_toml = version_dir.join("cabin.toml");
            let has_port = port_toml.is_file();
            let has_overlay = overlay_toml.is_file();

            // A directory with neither file is not a recipe (e.g. a
            // future non-version subdirectory); skip it. A directory
            // with only one of the two is a malformed recipe; fail loudly.
            if !has_port && !has_overlay {
                continue;
            }
            assert!(
                has_port && has_overlay,
                "incomplete foundation port at {}: both port.toml and cabin.toml are required",
                version_dir.display(),
            );

            println!("cargo:rerun-if-changed={}", port_toml.display());
            println!("cargo:rerun-if-changed={}", overlay_toml.display());
            entries.push((name.clone(), version, port_toml, overlay_toml));
        }
    }

    // Deterministic order so `iter()` is stable across builds.
    entries.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from the ports/ directory. Do not edit.\n");
    out.push_str("const BUILTIN: &[BuiltinPort] = &[\n");
    for (name, version, port_toml, overlay_toml) in &entries {
        write!(
            out,
            "    BuiltinPort {{\n        \
             name: \"{name}\",\n        \
             version: \"{version}\",\n        \
             port_toml: include_str!(\"{port}\"),\n        \
             overlay_toml: include_str!(\"{overlay}\"),\n    }},\n",
            name = escape(name),
            version = escape(version),
            port = escape(&port_toml.to_string_lossy()),
            overlay = escape(&overlay_toml.to_string_lossy()),
        )
        .unwrap();
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("builtin_generated.rs");
    fs::write(&out_path, out).expect("write generated builtin table");
}

/// Immediate child directories of `dir`, sorted by path. Returns an
/// empty list if `dir` does not exist or cannot be read.
fn child_dirs(dir: &Path) -> Vec<PathBuf> {
    let Ok(read) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut dirs: Vec<PathBuf> = read
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    dirs.sort();
    dirs
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .expect("port path component must be valid UTF-8")
        .to_owned()
}

/// Escape a string for embedding inside a Rust string literal.
fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
