//! Build script: generate the `BUILTIN` foundation-port table by
//! scanning the repository's `ports/` directory at compile time.
//!
//! Every `ports/<name>/<version>/` directory that contains both a
//! `port.toml` and an overlay `cabin.toml` is embedded automatically,
//! so adding a recipe directory is enough to bundle it - no manual
//! edits to `src/builtin.rs` are required.  The generated table is
//! written to `$OUT_DIR/builtin_generated.rs` and `include!`d by
//! `src/builtin.rs`.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // cabinpkg-port embeds the foundation-port recipes from the
    // crate-local `ports/` directory.  The recipes are committed here as
    // real files (the repository's top-level `ports/` is a symlink to
    // this directory), so they are present in every checkout and are
    // packaged into the published crate as regular files - bundling does
    // not depend on a symlink materializing on the build machine.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ports_dir = manifest_dir.join("ports");

    // Fail loudly if the recipes are missing instead of silently
    // emitting an empty BUILTIN table, which would leave every
    // `{ port = true }` dependency unresolvable.
    assert!(
        ports_dir.is_dir(),
        "foundation-port recipes not found at {}; the crate-local ports/ directory is missing.",
        ports_dir.display(),
    );

    // Rerun whenever anything under ports/ changes: a new or removed
    // recipe directory, or edited port.toml / cabin.toml contents.
    println!("cargo:rerun-if-changed={}", ports_dir.display());

    let mut entries = Vec::new();
    for name_dir in child_dirs(&ports_dir) {
        let name = file_name(&name_dir);
        for version_dir in child_dirs(&name_dir) {
            let version = file_name(&version_dir);
            let port_toml = version_dir.join("port.toml");
            let overlay_toml = version_dir.join("cabin.toml");
            let has_port = port_toml.is_file();
            let has_overlay = overlay_toml.is_file();

            // A directory with neither file is not a recipe (e.g. a
            // future non-version subdirectory); skip it.  A directory
            // with only one of the two is a malformed recipe; fail loudly.
            if !has_port && !has_overlay {
                continue;
            }
            assert!(
                has_port && has_overlay,
                "incomplete foundation port at {}: both port.toml and cabin.toml are required",
                version_dir.display(),
            );

            println!("cargo:rerun-if-changed={}", port_toml.display());
            println!("cargo:rerun-if-changed={}", overlay_toml.display());

            let patches = collect_patch_files(&version_dir);
            entries.push((name.clone(), version, port_toml, overlay_toml, patches));
        }
    }

    // Deterministic order so `iter()` is stable across builds.
    entries.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from the ports/ directory. Do not edit.\n");
    out.push_str("const BUILTIN: &[BuiltinPort] = &[\n");
    for (name, version, port_toml, overlay_toml, patches) in &entries {
        let mut patch_entries = String::new();
        for (rel, file) in patches {
            write!(
                patch_entries,
                "(\"{rel}\", include_bytes!(\"{file}\")), ",
                rel = escape(rel),
                file = escape(&file.to_string_lossy()),
            )
            .unwrap();
        }
        write!(
            out,
            "    BuiltinPort {{\n        \
             name: \"{name}\",\n        \
             version: \"{version}\",\n        \
             port_toml: include_str!(\"{port}\"),\n        \
             overlay_toml: include_str!(\"{overlay}\"),\n        \
             patches: &[{patch_entries}],\n    }},\n",
            name = escape(name),
            version = escape(version),
            port = escape(&port_toml.to_string_lossy()),
            overlay = escape(&overlay_toml.to_string_lossy()),
        )
        .unwrap();
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("builtin_generated.rs");
    fs::write(&out_path, out).expect("write generated builtin table");
}

/// Collect the files directly under `<version_dir>/patches/` as
/// `("patches/<name>", path)` pairs, sorted by name, and emit a
/// `rerun-if-changed` for each.  A bundled recipe's declared
/// `patches = ["patches/<file>"]` entries resolve against this
/// embedded set with no filesystem access at run time; the directory
/// is optional and most ports have none.
///
/// Every classification uses `symlink_metadata` (does not follow
/// links): embedding through a symlink would pull a host-local file
/// outside the recipe into the binary, making the bundled recipe
/// differ from filesystem preparation (which rejects escaping patch
/// symlinks) and the generated table depend on the build host.  A
/// symlinked `patches/` directory or a symlinked patch file is a
/// malformed recipe and fails loudly, like the incomplete-port case.
fn collect_patch_files(version_dir: &Path) -> Vec<(String, PathBuf)> {
    let patches_dir = version_dir.join("patches");
    // A real directory is processed, an absent one is skipped, and
    // anything else - a symlink (even to a directory) or a plain file
    // named `patches` - is rejected.  Silently skipping a symlinked
    // directory would embed an empty patch table and leave
    // preparation to fail later with `MissingPatchFile`.
    match patches_dir.symlink_metadata() {
        Ok(meta) => assert!(
            meta.is_dir() && !meta.file_type().is_symlink(),
            "foundation port `patches` at {} must be a real directory, not a symlink or file",
            patches_dir.display(),
        ),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Vec::new(),
        Err(err) => panic!("cannot stat {}: {err}", patches_dir.display()),
    }

    let mut files: Vec<PathBuf> = Vec::new();
    for entry in fs::read_dir(&patches_dir).expect("read patches directory") {
        let path = entry.expect("read patches entry").path();
        let file_type = path
            .symlink_metadata()
            .expect("stat patches entry")
            .file_type();
        assert!(
            !file_type.is_symlink(),
            "foundation port patch `{}` is a symlink; patch files must be regular files inside \
             the recipe",
            path.display(),
        );
        if file_type.is_file() {
            files.push(path);
        }
    }
    files.sort();
    files
        .into_iter()
        .map(|file| {
            println!("cargo:rerun-if-changed={}", file.display());
            (format!("patches/{}", file_name(&file)), file)
        })
        .collect()
}

/// Immediate child directories of `dir`, sorted by path.  Returns an
/// empty list if `dir` does not exist or cannot be read.
fn child_dirs(dir: &Path) -> Vec<PathBuf> {
    let Ok(read) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut dirs: Vec<PathBuf> = read
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    dirs.sort();
    dirs
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .expect("port path component must be valid UTF-8")
        .to_owned()
}

/// Escape a string for embedding inside a Rust string literal.
fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
