[package]
name = "fmt-usage"
version = "0.1.0"
cxx-standard = "c++17"

[dependencies]
fmt = { port = true, version = "^12" }

[target.fmt-usage]
type = "executable"
sources = ["src/main.cc"]
deps = ["fmt"]
