version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  gcc_7:
    docker:
      - image: matken11235/poac:gcc-7
    environment:
      CXX: g++
    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: ./poac install
      - run: ./poac test
      - run: ./poac --help
  gcc_8:
    docker:
      - image: matken11235/poac:gcc-8
    environment:
      CXX: g++
    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: ./poac install
      - run: ./poac test
      - run: ./poac --help
  gh_pages:
    working_directory: ~/poac/docs
    docker:
      - image: node:10
    steps:
      - checkout
      - run: git config --global user.name $USERNAME
      - run: git config --global user.email $EMAIL
      - run: cp -r .circleci docs
      - run: cd docs && npm i
      - run: cd docs && npm run build
      - run: cd docs && npm run publish
#  clang_5:
#    docker:
#      - image: matken11235/poac:clang-5.0
#    steps:
#      - checkout
#      - run: cmake .
#      - run: make
#      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
#      - run: ./poac --help
#  clang_6:
#    docker:
#      - image: matken11235/poac:clang-6.0
#    steps:
#      - checkout
#      - run: cmake .
#      - run: make
#      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
#      - run: ./poac --help

workflows:
  version: 2
  build_and_test:
    jobs:
      # GCC
      - gcc_7
      - gcc_8
      - gh_pages
      # Clang
#      - clang_5
#      - clang_6
