[package]
name = "picohttpparser-usage"
version = "0.1.0"

[dependencies]
picohttpparser = { port = true, version = "^2026" }

[target.picohttpparser-usage]
type = "executable"
sources = ["src/main.c"]
deps = ["picohttpparser"]
