//! Scaffold a fresh single-package layout (manifest + minimal C++
//! source tree) at a target directory.
//!
//! Used by both `cabin init` (initialise the current directory)
//! and `cabin new <path>` (create a new directory and initialise
//! it).  The two CLI surfaces call into [`scaffold`] so the
//! generated bytes stay identical across them.
//!
//! The scaffold kind ([`ScaffoldKind::Binary`] /
//! [`ScaffoldKind::Library`]) selects between an executable
//! (`cpp_executable`) and a library (`cpp_library`) package
//! layout.  The package-kind selection is the only knob that
//! changes the generated files; everything else stays
//! deterministic.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use atomic_write_file::AtomicWriteFile;
use cabin_core::PackageName;
use thiserror::Error;

/// Conventional manifest filename used by every Cabin command.
pub const MANIFEST_FILENAME: &str = "cabin.toml";

/// Fallback package name used when neither `--name` nor the target
/// directory's final component yield a usable package identifier.
pub const FALLBACK_PACKAGE_NAME: &str = "cabin-package";

/// Minimal C++ executable body emitted alongside a binary-package
/// manifest.
pub const BINARY_MAIN_CC_TEMPLATE: &str = "#include <iostream>\n\nint main() {\n    std::cout << \"Hello from Cabin\\n\";\n    return 0;\n}\n";

/// Conventional `.gitignore` body emitted by `cabin new` and by
/// `cabin init` when one does not already exist.  Cabin's default
/// build directory is `build/`; `dist/` is the default packaging
/// output directory.  `cabin.lock` is intentionally not ignored —
/// users are expected to commit it so collaborators converge on
/// the same resolution (see `docs/lockfile.md`).
pub const GITIGNORE_TEMPLATE: &str = "/build/\n/dist/\n";

/// What scaffold kind to generate.  Binary produces an executable
/// package; library produces a `cpp_library` package with a
/// public header under `include/` and an implementation source
/// under `src/`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ScaffoldKind {
    /// Single-target binary (`cpp_executable`).  This is the
    /// default both for `cabin new` and `cabin init`.
    #[default]
    Binary,
    /// Single-target library (`cpp_library`) with a minimal
    /// public header and implementation source.
    Library,
}

impl ScaffoldKind {
    /// Short human-readable label used in reporter output.
    /// `cabin new` / `cabin init` render the label inside the
    /// "Created `<label>` `<name>` package" status line.
    pub fn label(self) -> &'static str {
        match self {
            Self::Binary => "binary (application)",
            Self::Library => "library",
        }
    }
}

/// Typed request for [`scaffold`].  Construct with
/// [`ScaffoldRequest::new`] for the default (binary, no
/// `.gitignore`) and adjust before passing to the scaffold
/// function.
#[derive(Debug, Clone, Copy)]
pub struct ScaffoldRequest<'a> {
    /// Directory the scaffold writes into.  Must already exist
    /// and be a directory.  Callers that want to create a
    /// brand-new directory (`cabin new <path>`) are responsible
    /// for creating it first so they can decide how to clean up
    /// on failure.
    pub dest_dir: &'a Path,
    /// Explicit package name override.  When `None`, the default
    /// is derived from the final component of `dest_dir`, falling
    /// back to [`FALLBACK_PACKAGE_NAME`] when that component is
    /// unusable as a package identifier.
    pub name_override: Option<&'a str>,
    /// Scaffold kind.  Selects between binary and library
    /// layouts.
    pub kind: ScaffoldKind,
    /// Whether to write a `.gitignore` when one does not already
    /// exist.  `cabin new` passes `true`; `cabin init` passes
    /// `true` as well but [`scaffold`] never overwrites a
    /// pre-existing `.gitignore`.
    pub emit_gitignore: bool,
}

impl<'a> ScaffoldRequest<'a> {
    /// Build a default request that targets `dest_dir`.  The
    /// kind defaults to [`ScaffoldKind::Binary`], no
    /// `.gitignore` is emitted, and the package name is derived
    /// from the target directory.
    pub fn new(dest_dir: &'a Path) -> Self {
        Self {
            dest_dir,
            name_override: None,
            kind: ScaffoldKind::Binary,
            emit_gitignore: false,
        }
    }

    /// Set the package name override.
    pub fn with_name(mut self, name: Option<&'a str>) -> Self {
        self.name_override = name;
        self
    }

    /// Set the scaffold kind.
    pub fn with_kind(mut self, kind: ScaffoldKind) -> Self {
        self.kind = kind;
        self
    }

    /// Enable `.gitignore` emission (only writes the file when
    /// none exists at the destination).
    pub fn with_gitignore(mut self, emit: bool) -> Self {
        self.emit_gitignore = emit;
        self
    }
}

/// Outcome of a successful [`scaffold`] call.
#[derive(Debug, Clone)]
pub struct ScaffoldReport {
    /// Validated package name written into the manifest.
    pub name: PackageName,
    /// Scaffold kind that was generated.
    pub kind: ScaffoldKind,
    /// Files newly written by this call, in deterministic order.
    /// Pre-existing files that were intentionally preserved
    /// (`src/main.cc`, `.gitignore`) are not listed here.
    pub files_created: Vec<PathBuf>,
}

/// Errors produced while scaffolding a new package layout.
#[derive(Debug, Error)]
pub enum ScaffoldError {
    /// Package name is empty or contains whitespace.
    #[error("invalid package name; names must not be empty or contain whitespace")]
    EmptyOrWhitespaceName,

    /// Package name contains characters outside the supported alphabet.
    #[error(
        "package name {name:?} contains characters not supported (allowed: ASCII letters, digits, '_', '-')"
    )]
    UnsupportedNameCharacters { name: String },

    /// A `cabin.toml` already exists at the target directory.
    #[error("{MANIFEST_FILENAME} already exists at {}", path.display())]
    ManifestAlreadyExists { path: PathBuf },

    /// Filesystem IO failure when creating directories or writing
    /// generated files.
    #[error("failed to write {}: {source}", path.display())]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// Scaffold a fresh single-package layout into `request.dest_dir`.
///
/// On success a `cabin.toml` plus the kind-specific source tree
/// are written into the destination directory, and a
/// [`ScaffoldReport`] is returned describing what was produced.
///
/// Pre-existing user files are never overwritten:
/// - an existing `cabin.toml` is rejected with
///   [`ScaffoldError::ManifestAlreadyExists`];
/// - an existing `src/main.cc`, public header, or implementation
///   source is preserved unchanged;
/// - an existing `.gitignore` is preserved unchanged regardless
///   of `request.emit_gitignore`.
pub fn scaffold(request: ScaffoldRequest<'_>) -> Result<ScaffoldReport, ScaffoldError> {
    let raw_name = request.name_override.map_or_else(
        || default_package_name_from_dir(request.dest_dir),
        str::to_owned,
    );
    let name = validate_package_name(raw_name)?;

    let manifest_path = request.dest_dir.join(MANIFEST_FILENAME);
    if manifest_path.exists() {
        return Err(ScaffoldError::ManifestAlreadyExists {
            path: manifest_path,
        });
    }

    let mut files_created = Vec::new();

    let manifest_body = render_manifest(name.as_str(), request.kind);
    write_new_file(&manifest_path, manifest_body.as_bytes())?;
    files_created.push(manifest_path);

    let src_dir = request.dest_dir.join("src");
    create_dir_all(&src_dir)?;

    match request.kind {
        ScaffoldKind::Binary => {
            let main_cc = src_dir.join("main.cc");
            if !main_cc.exists() {
                write_new_file(&main_cc, BINARY_MAIN_CC_TEMPLATE.as_bytes())?;
                files_created.push(main_cc);
            }
        }
        ScaffoldKind::Library => {
            let stems = LibraryStems::from_package_name(name.as_str());
            let include_root = request.dest_dir.join("include");
            let include_pkg_dir = include_root.join(&stems.include_subdir);
            create_dir_all(&include_pkg_dir)?;

            let header_path = include_pkg_dir.join(&stems.header_filename);
            if !header_path.exists() {
                let header_body = render_library_header(&stems);
                write_new_file(&header_path, header_body.as_bytes())?;
                files_created.push(header_path);
            }

            let src_path = src_dir.join(&stems.source_filename);
            if !src_path.exists() {
                let source_body = render_library_source(&stems);
                write_new_file(&src_path, source_body.as_bytes())?;
                files_created.push(src_path);
            }
        }
    }

    if request.emit_gitignore {
        let gitignore_path = request.dest_dir.join(".gitignore");
        if !gitignore_path.exists() {
            write_new_file(&gitignore_path, GITIGNORE_TEMPLATE.as_bytes())?;
            files_created.push(gitignore_path);
        }
    }

    Ok(ScaffoldReport {
        name,
        kind: request.kind,
        files_created,
    })
}

/// Render the deterministic single-package manifest template for
/// `name` and `kind`.  The template carries a `[package]` section
/// with the supplied name plus a single target wired to the
/// kind-appropriate source layout.
pub fn render_manifest(name: &str, kind: ScaffoldKind) -> String {
    match kind {
        ScaffoldKind::Binary => render_binary_manifest(name),
        ScaffoldKind::Library => render_library_manifest(name),
    }
}

fn render_binary_manifest(name: &str) -> String {
    format!(
        "[package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         \n\
         [target.{name}]\n\
         type = \"cpp_executable\"\n\
         sources = [\"src/main.cc\"]\n"
    )
}

fn render_library_manifest(name: &str) -> String {
    let stems = LibraryStems::from_package_name(name);
    format!(
        "[package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         \n\
         [target.{name}]\n\
         type = \"cpp_library\"\n\
         sources = [\"src/{src}\"]\n\
         include_dirs = [\"include\"]\n",
        src = stems.source_filename,
    )
}

fn render_library_header(stems: &LibraryStems) -> String {
    format!(
        "#pragma once\n\
         \n\
         namespace {ns} {{\n\
         \n\
         int add(int a, int b);\n\
         \n\
         }}  // namespace {ns}\n",
        ns = stems.namespace,
    )
}

fn render_library_source(stems: &LibraryStems) -> String {
    format!(
        "#include \"{include}\"\n\
         \n\
         namespace {ns} {{\n\
         \n\
         int add(int a, int b) {{\n\
         \x20   return a + b;\n\
         }}\n\
         \n\
         }}  // namespace {ns}\n",
        include = stems.header_include_path,
        ns = stems.namespace,
    )
}

/// Filename / identifier stems used by the library scaffold.
/// Derived deterministically from the validated package name so
/// callers never have to re-implement the conversion.
#[derive(Debug, Clone, PartialEq, Eq)]
struct LibraryStems {
    /// Subdirectory under `include/` (matches the package name).
    include_subdir: String,
    /// Header filename: `<package_name>.hpp`.
    header_filename: String,
    /// Implementation filename: `<package_name>.cc`.
    source_filename: String,
    /// Include path used inside the implementation source.
    header_include_path: String,
    /// Sanitised identifier suitable for a C++ namespace
    /// declaration: ASCII letters, digits and `_`.  Derived from
    /// the package name by replacing `-` with `_`.
    namespace: String,
}

impl LibraryStems {
    fn from_package_name(name: &str) -> Self {
        let namespace = sanitise_identifier(name);
        Self {
            include_subdir: name.to_owned(),
            header_filename: format!("{name}.hpp"),
            source_filename: format!("{name}.cc"),
            header_include_path: format!("{name}/{name}.hpp"),
            namespace,
        }
    }
}

/// Convert a validated package name (ASCII alphanumeric / `_` /
/// `-`) into an identifier that is safe to drop into generated
/// C/C++ source.  The conversion is narrow and deterministic:
///
/// - `-` is mapped to `_`;
/// - if the first character is an ASCII digit, a leading `_` is
///   prepended so the result is a valid C++ identifier (which
///   may not start with a digit).
///
/// The input is already validated by [`validate_package_name`],
/// so the output is guaranteed to be a non-empty sequence of
/// ASCII letters, digits, and `_` that starts with a letter or
/// `_`.
fn sanitise_identifier(raw: &str) -> String {
    let mut out: String = raw
        .chars()
        .map(|c| if c == '-' { '_' } else { c })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Derive the default package name from a target directory.
/// Returns [`FALLBACK_PACKAGE_NAME`] when the final path component
/// is missing, non-UTF-8, or fails the bare-key alphabet.
pub(crate) fn default_package_name_from_dir(dest_dir: &Path) -> String {
    let candidate = dest_dir.file_name().and_then(|s| s.to_str()).unwrap_or("");
    if is_bare_toml_key(candidate) {
        candidate.to_owned()
    } else {
        FALLBACK_PACKAGE_NAME.to_owned()
    }
}

/// Whether `s` is non-empty and contains only ASCII letters,
/// digits, `_`, or `-`.  This is the alphabet `cabin init` and
/// `cabin new` accept for the generated package name; it is a
/// strict subset of [`PackageName`]'s registry-safety grammar.
pub(crate) fn is_bare_toml_key(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

fn validate_package_name(raw: String) -> Result<PackageName, ScaffoldError> {
    let trimmed_empty = raw.is_empty() || raw.chars().any(char::is_whitespace);
    if trimmed_empty {
        return Err(ScaffoldError::EmptyOrWhitespaceName);
    }
    if !is_bare_toml_key(&raw) {
        return Err(ScaffoldError::UnsupportedNameCharacters { name: raw });
    }
    PackageName::new(raw).map_err(|_| ScaffoldError::EmptyOrWhitespaceName)
}

fn create_dir_all(path: &Path) -> Result<(), ScaffoldError> {
    std::fs::create_dir_all(path).map_err(|source| ScaffoldError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn write_new_file(path: &Path, body: &[u8]) -> Result<(), ScaffoldError> {
    let io_err = |source| ScaffoldError::Io {
        path: path.to_path_buf(),
        source,
    };
    let mut file = AtomicWriteFile::open(path).map_err(io_err)?;
    file.write_all(body).map_err(io_err)?;
    file.commit().map_err(io_err)
}

#[cfg(test)]
mod tests {
    use super::*;

    use assert_fs::TempDir;
    use assert_fs::prelude::*;
    use predicates::prelude::*;

    fn binary_request(dest: &Path) -> ScaffoldRequest<'_> {
        ScaffoldRequest::new(dest).with_name(Some("hello"))
    }

    #[test]
    fn rendered_binary_template_carries_project_and_target_sections() {
        let manifest = render_manifest("hello", ScaffoldKind::Binary);
        assert!(manifest.contains("[package]"));
        assert!(manifest.contains(r#"name = "hello""#));
        assert!(manifest.contains("[target.hello]"));
        assert!(manifest.contains(r#"type = "cpp_executable""#));
        assert!(manifest.contains(r#"sources = ["src/main.cc"]"#));
    }

    #[test]
    fn rendered_library_template_carries_cpp_library_target() {
        let manifest = render_manifest("hello", ScaffoldKind::Library);
        assert!(manifest.contains("[package]"));
        assert!(manifest.contains(r#"name = "hello""#));
        assert!(manifest.contains("[target.hello]"));
        assert!(manifest.contains(r#"type = "cpp_library""#));
        assert!(manifest.contains(r#"sources = ["src/hello.cc"]"#));
        assert!(manifest.contains(r#"include_dirs = ["include"]"#));
    }

    #[test]
    fn fallback_package_name_when_dir_invalid() {
        let path = Path::new("/");
        assert_eq!(default_package_name_from_dir(path), FALLBACK_PACKAGE_NAME);
    }

    #[test]
    fn directory_name_used_when_valid() {
        let path = Path::new("/tmp/sample-package");
        assert_eq!(default_package_name_from_dir(path), "sample-package");
    }

    #[test]
    fn dotted_directory_name_falls_back() {
        let path = Path::new("/tmp/.tmpAbCdEf");
        assert_eq!(default_package_name_from_dir(path), FALLBACK_PACKAGE_NAME);
    }

    #[test]
    fn is_bare_toml_key_acceptance() {
        assert!(is_bare_toml_key("hello"));
        assert!(is_bare_toml_key("hello-world"));
        assert!(is_bare_toml_key("hello_world"));
        assert!(is_bare_toml_key("h123"));
        assert!(!is_bare_toml_key(""));
        assert!(!is_bare_toml_key("hello.world"));
        assert!(!is_bare_toml_key("hello world"));
        assert!(!is_bare_toml_key(".hidden"));
    }

    #[test]
    fn sanitise_identifier_replaces_hyphens() {
        assert_eq!(sanitise_identifier("hello"), "hello");
        assert_eq!(sanitise_identifier("hello-world"), "hello_world");
        assert_eq!(sanitise_identifier("a-b-c"), "a_b_c");
        assert_eq!(sanitise_identifier("hello_world"), "hello_world");
    }

    #[test]
    fn sanitise_identifier_prepends_underscore_for_leading_digit() {
        assert_eq!(sanitise_identifier("1cool"), "_1cool");
        assert_eq!(sanitise_identifier("0123"), "_0123");
        assert_eq!(sanitise_identifier("1-2-3"), "_1_2_3");
    }

    #[test]
    fn scaffold_library_with_leading_digit_emits_valid_cpp_namespace() {
        let dir = TempDir::new().unwrap();
        let request = ScaffoldRequest::new(dir.path())
            .with_name(Some("9lives"))
            .with_kind(ScaffoldKind::Library);
        scaffold(request).unwrap();

        let header =
            std::fs::read_to_string(dir.child("include/9lives/9lives.hpp").path()).unwrap();
        assert!(
            header.contains("namespace _9lives"),
            "namespace must start with `_` for digit-leading names: {header}"
        );
        let src = std::fs::read_to_string(dir.child("src/9lives.cc").path()).unwrap();
        assert!(src.contains("namespace _9lives"));
    }

    #[test]
    fn library_stems_use_package_name_and_sanitised_namespace() {
        let stems = LibraryStems::from_package_name("hello-world");
        assert_eq!(stems.include_subdir, "hello-world");
        assert_eq!(stems.header_filename, "hello-world.hpp");
        assert_eq!(stems.source_filename, "hello-world.cc");
        assert_eq!(stems.header_include_path, "hello-world/hello-world.hpp");
        assert_eq!(stems.namespace, "hello_world");
    }

    #[test]
    fn scaffold_binary_creates_manifest_and_main_cc() {
        let dir = TempDir::new().unwrap();
        let report = scaffold(binary_request(dir.path())).unwrap();
        assert_eq!(report.name.as_str(), "hello");
        assert_eq!(report.kind, ScaffoldKind::Binary);

        let manifest_text = std::fs::read_to_string(dir.child("cabin.toml").path()).unwrap();
        assert!(manifest_text.contains("[package]"));
        assert!(manifest_text.contains(r#"name = "hello""#));
        assert!(manifest_text.contains(r#"type = "cpp_executable""#));

        let main_cc = std::fs::read_to_string(dir.child("src/main.cc").path()).unwrap();
        assert!(main_cc.contains("int main"));
    }

    #[test]
    fn scaffold_library_creates_header_and_implementation() {
        let dir = TempDir::new().unwrap();
        let request = ScaffoldRequest::new(dir.path())
            .with_name(Some("hello"))
            .with_kind(ScaffoldKind::Library);
        let report = scaffold(request).unwrap();
        assert_eq!(report.name.as_str(), "hello");
        assert_eq!(report.kind, ScaffoldKind::Library);

        let manifest_text = std::fs::read_to_string(dir.child("cabin.toml").path()).unwrap();
        assert!(manifest_text.contains(r#"type = "cpp_library""#));
        assert!(manifest_text.contains(r#"sources = ["src/hello.cc"]"#));
        assert!(manifest_text.contains(r#"include_dirs = ["include"]"#));

        let header = std::fs::read_to_string(dir.child("include/hello/hello.hpp").path()).unwrap();
        assert!(header.contains("#pragma once"));
        assert!(header.contains("namespace hello"));
        assert!(header.contains("int add(int a, int b);"));

        let src = std::fs::read_to_string(dir.child("src/hello.cc").path()).unwrap();
        assert!(src.contains(r#"#include "hello/hello.hpp""#));
        assert!(src.contains("namespace hello"));
        assert!(src.contains("return a + b;"));
    }

    #[test]
    fn scaffold_library_sanitises_hyphenated_namespace() {
        let dir = TempDir::new().unwrap();
        let request = ScaffoldRequest::new(dir.path())
            .with_name(Some("hello-world"))
            .with_kind(ScaffoldKind::Library);
        scaffold(request).unwrap();

        let header =
            std::fs::read_to_string(dir.child("include/hello-world/hello-world.hpp").path())
                .unwrap();
        assert!(header.contains("namespace hello_world"));
        let src = std::fs::read_to_string(dir.child("src/hello-world.cc").path()).unwrap();
        assert!(src.contains(r#"#include "hello-world/hello-world.hpp""#));
        assert!(src.contains("namespace hello_world"));
    }

    #[test]
    fn scaffold_emits_gitignore_when_requested() {
        let dir = TempDir::new().unwrap();
        let request = binary_request(dir.path()).with_gitignore(true);
        scaffold(request).unwrap();

        let body = std::fs::read_to_string(dir.child(".gitignore").path()).unwrap();
        assert!(body.contains("/build/"));
        assert!(body.contains("/dist/"));
        assert!(
            !body.contains("cabin.lock"),
            ".gitignore must not ignore cabin.lock: {body}"
        );
    }

    #[test]
    fn scaffold_does_not_emit_gitignore_when_not_requested() {
        let dir = TempDir::new().unwrap();
        scaffold(binary_request(dir.path())).unwrap();
        dir.child(".gitignore").assert(predicate::path::missing());
    }

    #[test]
    fn scaffold_preserves_existing_gitignore() {
        let dir = TempDir::new().unwrap();
        let gitignore = dir.child(".gitignore");
        gitignore.write_str("# user gitignore\n").unwrap();
        let request = binary_request(dir.path()).with_gitignore(true);
        scaffold(request).unwrap();
        let after = std::fs::read_to_string(gitignore.path()).unwrap();
        assert_eq!(after, "# user gitignore\n");
    }

    #[test]
    fn scaffold_rejects_existing_manifest() {
        let dir = TempDir::new().unwrap();
        dir.child("cabin.toml")
            .write_str("# preexisting\n")
            .unwrap();
        let err = scaffold(binary_request(dir.path())).unwrap_err();
        assert!(matches!(err, ScaffoldError::ManifestAlreadyExists { .. }));
        let displayed = format!("{err}");
        assert!(
            displayed.contains("cabin.toml already exists"),
            "unexpected error display: {displayed}"
        );
    }

    #[test]
    fn scaffold_preserves_existing_main_cc() {
        let dir = TempDir::new().unwrap();
        let main_cc = dir.child("src/main.cc");
        let preexisting = "// user code\n";
        main_cc.write_str(preexisting).unwrap();

        scaffold(binary_request(dir.path())).unwrap();
        let after = std::fs::read_to_string(main_cc.path()).unwrap();
        assert_eq!(after, preexisting);
    }

    #[test]
    fn scaffold_library_preserves_existing_header_and_source() {
        let dir = TempDir::new().unwrap();
        let header = dir.child("include/hello/hello.hpp");
        let source = dir.child("src/hello.cc");
        let preexisting_header = "// user header\n";
        let preexisting_source = "// user source\n";
        header.write_str(preexisting_header).unwrap();
        source.write_str(preexisting_source).unwrap();

        let request = ScaffoldRequest::new(dir.path())
            .with_name(Some("hello"))
            .with_kind(ScaffoldKind::Library);
        scaffold(request).unwrap();

        let after_header = std::fs::read_to_string(header.path()).unwrap();
        let after_source = std::fs::read_to_string(source.path()).unwrap();
        assert_eq!(after_header, preexisting_header);
        assert_eq!(after_source, preexisting_source);
    }

    #[test]
    fn scaffold_rejects_invalid_name() {
        let dir = TempDir::new().unwrap();
        let request = binary_request(dir.path()).with_name(Some("foo bar"));
        let err = scaffold(request).unwrap_err();
        assert!(matches!(err, ScaffoldError::EmptyOrWhitespaceName));
    }

    #[test]
    fn scaffold_rejects_unsupported_characters() {
        let dir = TempDir::new().unwrap();
        let request = binary_request(dir.path()).with_name(Some("foo.bar"));
        let err = scaffold(request).unwrap_err();
        assert!(matches!(
            err,
            ScaffoldError::UnsupportedNameCharacters { .. }
        ));
    }

    #[test]
    fn scaffold_uses_directory_name_by_default() {
        let parent = TempDir::new().unwrap();
        let child = parent.child("derived-name");
        child.create_dir_all().unwrap();
        let report = scaffold(ScaffoldRequest::new(child.path())).unwrap();
        assert_eq!(report.name.as_str(), "derived-name");
    }

    #[test]
    fn scaffold_falls_back_when_directory_name_unusable() {
        let parent = TempDir::new().unwrap();
        let child = parent.child(".dotted");
        child.create_dir_all().unwrap();
        let report = scaffold(ScaffoldRequest::new(child.path())).unwrap();
        assert_eq!(report.name.as_str(), FALLBACK_PACKAGE_NAME);
    }

    #[test]
    fn scaffold_report_lists_files_in_deterministic_order() {
        let dir = TempDir::new().unwrap();
        let request = ScaffoldRequest::new(dir.path())
            .with_name(Some("hello"))
            .with_kind(ScaffoldKind::Library)
            .with_gitignore(true);
        let report = scaffold(request).unwrap();

        let suffixes: Vec<String> = report
            .files_created
            .iter()
            .map(|p| {
                p.strip_prefix(dir.path())
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/")
            })
            .collect();
        assert_eq!(
            suffixes,
            vec![
                "cabin.toml".to_string(),
                "include/hello/hello.hpp".to_string(),
                "src/hello.cc".to_string(),
                ".gitignore".to_string(),
            ]
        );
    }

    #[test]
    fn binary_and_library_manifests_are_byte_stable() {
        let one = render_manifest("hello", ScaffoldKind::Binary);
        let two = render_manifest("hello", ScaffoldKind::Binary);
        assert_eq!(one, two);
        let lib_one = render_manifest("hello", ScaffoldKind::Library);
        let lib_two = render_manifest("hello", ScaffoldKind::Library);
        assert_eq!(lib_one, lib_two);
    }
}
