//! Publish validation against real `cabin package` output.
//!
//! Two layers, one validation path:
//! - the frozen pair under `tests/fixtures/` runs offline in every
//!   `cargo test` (plus mutation checks proving the rejections fire);
//! - the `#[ignore]`d conformance test feeds pairs freshly generated by
//!   `scripts/gen-fixtures.sh` (the in-tree cabin binary) through the same
//!   path, so client and server cannot silently drift. CI runs it as the
//!   dedicated `conformance` job in `.github/workflows/registry.yml`.

use std::fmt::Write as _;

use cabin_registry_worker::publish::{
    CHECKSUM_MISMATCH, IDENTITY_MISMATCH, METADATA_NOT_CANONICAL, decode_frame, validate_metadata,
    verify_checksum,
};
use sha2::{Digest, Sha256};

const FROZEN_METADATA: &[u8] = include_bytes!("fixtures/smoke-withdep-0.2.0.json");
const FROZEN_ARCHIVE: &[u8] = include_bytes!("fixtures/smoke-withdep-0.2.0.tar.gz");

/// Client-side framing (`cabin_registry_api::encode_publish_body`).
fn frame(metadata: &[u8], archive: &[u8]) -> Vec<u8> {
    let mut body = Vec::with_capacity(8 + metadata.len() + archive.len());
    body.extend_from_slice(&u32::try_from(metadata.len()).unwrap().to_le_bytes());
    body.extend_from_slice(metadata);
    body.extend_from_slice(&u32::try_from(archive.len()).unwrap().to_le_bytes());
    body.extend_from_slice(archive);
    body
}

/// What the wasm glue computes with `SubtleCrypto`, the host computes
/// with `sha2`: the lowercase SHA-256 hex of the archive bytes.
fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .fold(String::with_capacity(64), |mut hex, byte| {
            let _ = write!(hex, "{byte:02x}");
            hex
        })
}

/// The full server-side validation path for one framed publish body, as
/// `glue::publish_response` runs it: decode, metadata validation, digest
/// comparison.
fn validate_pair(
    scope: &str,
    name: &str,
    version: &str,
    metadata: &[u8],
    archive: &[u8],
) -> Result<(), &'static str> {
    let body = frame(metadata, archive);
    let frame = decode_frame(&body)?;
    let parsed = validate_metadata(scope, name, version, frame.metadata)?;
    verify_checksum(&parsed, &sha256_hex(frame.archive))
}

#[test]
fn frozen_fixture_passes_the_full_validation_path() {
    validate_pair("smoke", "withdep", "0.2.0", FROZEN_METADATA, FROZEN_ARCHIVE).unwrap();
}

#[test]
fn frozen_fixture_under_a_different_scope_is_rejected() {
    // The document's scoped name binds it to one URL pair; another
    // scope's URL can never claim it.
    assert_eq!(
        validate_pair(
            "otherscope",
            "withdep",
            "0.2.0",
            FROZEN_METADATA,
            FROZEN_ARCHIVE
        ),
        Err(IDENTITY_MISMATCH)
    );
}

#[test]
fn frozen_fixture_with_a_flipped_archive_byte_fails_the_checksum() {
    let mut archive = FROZEN_ARCHIVE.to_vec();
    let last = archive.len() - 1;
    archive[last] ^= 0x01;
    assert_eq!(
        validate_pair("smoke", "withdep", "0.2.0", FROZEN_METADATA, &archive),
        Err(CHECKSUM_MISMATCH)
    );
}

#[test]
fn frozen_fixture_with_an_extra_metadata_key_is_rejected() {
    let text = std::str::from_utf8(FROZEN_METADATA).unwrap();
    let with_extra = text.replace("\"schema\": 1,", "\"schema\": 1,\n  \"extra-key\": true,");
    assert_ne!(text, with_extra, "the mutation must have applied");
    assert_eq!(
        validate_pair(
            "smoke",
            "withdep",
            "0.2.0",
            with_extra.as_bytes(),
            FROZEN_ARCHIVE
        ),
        Err(METADATA_NOT_CANONICAL)
    );
}

/// Conformance against freshly generated pairs: run
/// `scripts/gen-fixtures.sh <dir>` first and point
/// `CABIN_REGISTRY_FIXTURES` at `<dir>`.
#[test]
#[ignore = "needs CABIN_REGISTRY_FIXTURES pointing at gen-fixtures.sh output"]
fn generated_fixtures_pass_the_full_validation_path() {
    let dir = std::env::var("CABIN_REGISTRY_FIXTURES")
        .expect("CABIN_REGISTRY_FIXTURES must point at the gen-fixtures.sh output directory");
    let mut checked = 0;
    for entry in std::fs::read_dir(&dir).expect("fixtures directory must be readable") {
        let metadata_path = entry.unwrap().path();
        if metadata_path.extension().is_none_or(|ext| ext != "json") {
            continue;
        }
        let archive_path = metadata_path.with_extension("tar.gz");
        let metadata = std::fs::read(&metadata_path).unwrap();
        let archive = std::fs::read(&archive_path)
            .unwrap_or_else(|err| panic!("archive for {metadata_path:?} must exist: {err}"));
        // The publish URL identity comes from the document itself: the
        // fixtures are scoped natively, exactly as the client uploads
        // them.
        let doc: serde_json::Value = serde_json::from_slice(&metadata).unwrap();
        let full_name = doc["name"]
            .as_str()
            .expect("fixture metadata declares a name");
        let (scope, name) = full_name
            .split_once('/')
            .expect("registry fixtures carry scoped names");
        let version = doc["version"]
            .as_str()
            .expect("fixture metadata declares a version");
        // Independent cross-check: the pair's filename must be the
        // flattened form of the identity the document declares, so a
        // fixture whose name drifted from its filename cannot pass by
        // validating against itself.
        let stem = metadata_path.file_stem().unwrap().to_str().unwrap();
        assert_eq!(
            stem,
            format!("{scope}-{name}-{version}"),
            "fixture filename must be the flattened metadata identity"
        );
        validate_pair(scope, name, version, &metadata, &archive)
            .unwrap_or_else(|detail| panic!("{full_name}@{version} failed validation: {detail}"));
        checked += 1;
    }
    assert!(
        checked >= 2,
        "expected at least the two gen-fixtures.sh pairs in {dir}, found {checked}"
    );
}
