//! Publish validation against real `cabin package` output.
//!
//! Two layers, one validation path:
//! - the frozen pair under `tests/fixtures/` runs offline in every
//!   `cargo test` (plus mutation checks proving the rejections fire);
//! - the `#[ignore]`d conformance test feeds pairs freshly generated by
//!   `scripts/gen-fixtures.sh` (the in-tree cabin binary) through the same
//!   path, so client and server cannot silently drift. CI runs it as the
//!   dedicated `conformance` job in `.github/workflows/registry.yml`.

use std::fmt::Write as _;
use std::path::Path;

use cabin_registry_worker::publish::{
    CHECKSUM_MISMATCH, IDENTITY_MISMATCH, METADATA_NOT_CANONICAL, decode_frame, validate_metadata,
    verify_checksum,
};
use sha2::{Digest, Sha256};

const FROZEN_METADATA: &[u8] = include_bytes!("fixtures/withdep-0.2.0.json");
const FROZEN_ARCHIVE: &[u8] = include_bytes!("fixtures/withdep-0.2.0.tar.gz");

/// The scope the bare client fixtures are published under here.
const SCOPE: &str = "testscope";

/// Client-side framing (`cabin_registry_api::encode_publish_body`).
fn frame(metadata: &[u8], archive: &[u8]) -> Vec<u8> {
    let mut body = Vec::with_capacity(8 + metadata.len() + archive.len());
    body.extend_from_slice(&u32::try_from(metadata.len()).unwrap().to_le_bytes());
    body.extend_from_slice(metadata);
    body.extend_from_slice(&u32::try_from(archive.len()).unwrap().to_le_bytes());
    body.extend_from_slice(archive);
    body
}

/// Rewrites a bare-name client fixture into the scoped shape the
/// registry accepts: `name` becomes `<scope>/<name>` and `source.path`
/// the scope-embedding canonical path. Mid-track shim: `cabin package`
/// still emits bare names until the client-side scoped-names steps land,
/// after which the fixtures are scoped natively and this rewrite (plus
/// [`SCOPE`]) goes away.
fn scoped(metadata: &[u8], scope: &str, name: &str, version: &str) -> Vec<u8> {
    let mut doc: serde_json::Value = serde_json::from_slice(metadata).unwrap();
    // Assert the exact pre-scopes shape of both rewritten fields: when
    // the client starts emitting scoped names, these fail and force the
    // shim's removal instead of silently double-rewriting.
    assert_eq!(doc["name"], name, "fixture must carry the bare name");
    assert_eq!(
        doc["source"]["path"],
        format!("../artifacts/{name}/{name}-{version}.tar.gz"),
        "fixture must carry the bare source path"
    );
    doc["name"] = format!("{scope}/{name}").into();
    doc["source"]["path"] =
        format!("../../artifacts/{scope}/{name}/{scope}-{name}-{version}.tar.gz").into();
    serde_json::to_vec(&doc).unwrap()
}

/// What the wasm glue computes with `SubtleCrypto`, the host computes
/// with `sha2`: the lowercase SHA-256 hex of the archive bytes.
fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .fold(String::with_capacity(64), |mut hex, byte| {
            let _ = write!(hex, "{byte:02x}");
            hex
        })
}

/// The full server-side validation path for one framed publish body, as
/// `glue::publish_response` runs it: decode, metadata validation, digest
/// comparison.
fn validate_pair(
    scope: &str,
    name: &str,
    version: &str,
    metadata: &[u8],
    archive: &[u8],
) -> Result<(), &'static str> {
    let body = frame(metadata, archive);
    let frame = decode_frame(&body)?;
    let parsed = validate_metadata(scope, name, version, frame.metadata)?;
    verify_checksum(&parsed, &sha256_hex(frame.archive))
}

#[test]
fn frozen_fixture_passes_the_full_validation_path() {
    let metadata = scoped(FROZEN_METADATA, SCOPE, "withdep", "0.2.0");
    validate_pair(SCOPE, "withdep", "0.2.0", &metadata, FROZEN_ARCHIVE).unwrap();
}

#[test]
fn frozen_fixture_with_a_bare_name_is_rejected() {
    // What the pre-scopes client uploads verbatim: the bare-name
    // document can never match a scoped URL.
    assert_eq!(
        validate_pair(SCOPE, "withdep", "0.2.0", FROZEN_METADATA, FROZEN_ARCHIVE),
        Err(IDENTITY_MISMATCH)
    );
}

#[test]
fn frozen_fixture_with_a_flipped_archive_byte_fails_the_checksum() {
    let metadata = scoped(FROZEN_METADATA, SCOPE, "withdep", "0.2.0");
    let mut archive = FROZEN_ARCHIVE.to_vec();
    let last = archive.len() - 1;
    archive[last] ^= 0x01;
    assert_eq!(
        validate_pair(SCOPE, "withdep", "0.2.0", &metadata, &archive),
        Err(CHECKSUM_MISMATCH)
    );
}

#[test]
fn frozen_fixture_with_an_extra_metadata_key_is_rejected() {
    let scoped = scoped(FROZEN_METADATA, SCOPE, "withdep", "0.2.0");
    let text = std::str::from_utf8(&scoped).unwrap();
    let with_extra = text.replace("\"schema\":1,", "\"schema\":1,\"extra-key\":true,");
    assert_ne!(text, with_extra, "the mutation must have applied");
    assert_eq!(
        validate_pair(
            SCOPE,
            "withdep",
            "0.2.0",
            with_extra.as_bytes(),
            FROZEN_ARCHIVE
        ),
        Err(METADATA_NOT_CANONICAL)
    );
}

/// Conformance against freshly generated pairs: run
/// `scripts/gen-fixtures.sh <dir>` first and point
/// `CABIN_REGISTRY_FIXTURES` at `<dir>`.
#[test]
#[ignore = "needs CABIN_REGISTRY_FIXTURES pointing at gen-fixtures.sh output"]
fn generated_fixtures_pass_the_full_validation_path() {
    let dir = std::env::var("CABIN_REGISTRY_FIXTURES")
        .expect("CABIN_REGISTRY_FIXTURES must point at the gen-fixtures.sh output directory");
    let mut checked = 0;
    for entry in std::fs::read_dir(&dir).expect("fixtures directory must be readable") {
        let metadata_path = entry.unwrap().path();
        if metadata_path.extension().is_none_or(|ext| ext != "json") {
            continue;
        }
        let (name, version) = parse_pair_stem(&metadata_path);
        let archive_path = metadata_path.with_extension("tar.gz");
        let metadata = std::fs::read(&metadata_path).unwrap();
        let archive = std::fs::read(&archive_path)
            .unwrap_or_else(|err| panic!("archive for {metadata_path:?} must exist: {err}"));
        // The same mid-track scope injection as the frozen tests: the
        // in-tree client still packages bare names.
        let metadata = scoped(&metadata, SCOPE, &name, &version);
        validate_pair(SCOPE, &name, &version, &metadata, &archive)
            .unwrap_or_else(|detail| panic!("{name}@{version} failed validation: {detail}"));
        checked += 1;
    }
    assert!(
        checked >= 2,
        "expected at least the two gen-fixtures.sh pairs in {dir}, found {checked}"
    );
}

/// `<name>-<version>` from a fixture file stem, splitting at the first
/// hyphen followed by a digit (names may contain hyphens; fixture
/// versions start with a digit).
fn parse_pair_stem(path: &Path) -> (String, String) {
    let stem = path.file_stem().unwrap().to_str().unwrap();
    let Some((split, _)) = stem
        .match_indices('-')
        .find(|(idx, _)| stem.as_bytes().get(idx + 1).is_some_and(u8::is_ascii_digit))
    else {
        panic!("fixture stem {stem:?} is not <name>-<version>")
    };
    (stem[..split].to_owned(), stem[split + 1..].to_owned())
}
