[port]
name = "spdlog"
version = "1.17.0"
description = "Fast C++ logging library"
license = "MIT"
homepage = "https://github.com/gabime/spdlog"
upstream = "https://github.com/gabime/spdlog"

[source]
type = "archive"
url = "https://github.com/gabime/spdlog/archive/refs/tags/v1.17.0.tar.gz"
sha256 = "d8862955c6d74e5846b3f580b1605d2428b11d97a410d86e2fb13e857cd3a744"
strip_prefix = "spdlog-1.17.0"

[overlay]
manifest = "cabin.toml"
