name: "Setup Ubuntu dependencies"
description: "Setup Ubuntu dependencies"
runs:
  using: "composite"
  steps:
    - name: "Setup dependencies"
      shell: bash
      run: |
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive

        if [ "$(id -u)" -eq 0 ]; then
          SUDO=""
        elif command -v sudo >/dev/null 2>&1; then
          SUDO="sudo"
        else
          echo "ERROR: Need root privileges or sudo to install packages." >&2
          exit 1
        fi

        $SUDO apt-get update
        $SUDO apt-get install -y \
          wget make git lsb-release gnupg software-properties-common \
          libcurl4-openssl-dev \
          libfmt-dev \
          libspdlog-dev \
          libgit2-dev \
          ninja-build \
          nlohmann-json3-dev \
          libtbb-dev
