[package]
name = "sqlite-todo"
version = "0.1.0"
c-standard = "c11"

[dependencies]
"cabin-ports/sqlite3" = "=3.53.2"

[target.sqlite-todo]
type = "executable"
sources = ["src/main.c"]
deps = ["cabin-ports/sqlite3"]
