[package]
name = "nlohmann-json-usage"
version = "0.1.0"
cxx-standard = "c++17"

[dependencies]
"cabin-ports/nlohmann_json" = "=3.12.0"

[target.nlohmann-json-usage]
type = "executable"
sources = ["src/main.cc"]
deps = ["cabin-ports/nlohmann_json"]
