[package]
name = "uthash-usage"
version = "0.1.0"
c-standard = "c11"

[dependencies]
"cabin-ports/uthash" = "=2.4.0"

[target.uthash-usage]
type = "executable"
sources = ["src/main.c"]
deps = ["cabin-ports/uthash"]
