name: "Setup macOS dependencies"
description: "Setup macOS dependencies"

runs:
  using: "composite"
  steps:
    - name: "Setup dependencies"
      run: |
        brew install \
          curl \
          fmt \
          spdlog \
          libgit2 \
          nlohmann-json \
          tbb
      shell: "bash"
