//! The tokened preamble and the two planes it opens with, ported from
//! `registry/scripts/smoke.sh` L663-804: the verifier build, the frozen
//! fixture wiring, the two helpers every later verification leg calls
//! (`listing_entry` and `run_verifier`), the read plane a valid token
//! must not change, and the minted session through its ghost-identity
//! and CSRF legs.
//!
//! `as_publisher`/`as_verifier` (L663-664) are already
//! [`Smoke::as_publisher`]/[`Smoke::as_verifier`].  The session cookie
//! is the run's *second* mutable credential state (the plan's
//! runners-up note): it is minted here, swapped for the ghost's and
//! restored at L786-796, and carried forward to the legs that follow.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context as _, Result, bail};
use sha2::{Digest as _, Sha256};
use tempfile::TempDir;

use crate::bytes::{revision_of, sha256_hex};
use crate::context::{Base, Smoke};
use crate::legs::anonymous::uniform_401_with;
use crate::step;
use crate::text::{contains, read};

/// The frozen conformance fixture (`registry/tests/fixtures/`,
/// regenerated by `cargo gen-fixtures`) doubles as the smoke publish
/// payload verbatim: gen-fixtures authors its packages under the
/// `smoke` scope precisely so the pair this flow publishes matches the
/// scope claimed here (L681-683).
pub const SCOPE: &str = "smoke";
pub const NAME: &str = "withdep";
pub const VERSION: &str = "0.2.0";

/// L799's `create_body`, defined inside the CSRF step but read again by
/// the token round-trip that follows it (L808).
pub const CREATE_BODY: &str = r#"{"name":"smoke-session","scopes":["publish"]}"#;

/// What L670-723 leaves behind for every leg after it: the work
/// directory, the built verifier, the fixture pair as bytes *and* as
/// paths (the `wrangler r2 object put --file` and `shasum -c` sites
/// need real files), and the routes derived from the fixture's
/// packaging revision.
pub struct Setup {
    pub work: TempDir,
    pub verifier_bin: PathBuf,
    pub fixture_archive: PathBuf,
    pub fixture_metadata: PathBuf,
    pub fixture_zip: Vec<u8>,
    pub fixture_meta: Vec<u8>,
    pub blob_hash: String,
    pub rev: String,
    pub publish_path: String,
    pub package_path: String,
    pub artifact_path: String,
}

/// L670-699: build the verifier, wire the fixture, open the work
/// directory.
///
/// The verification legs run the same binary the GitHub Actions
/// verifier does, so the pending -> verified / rejected transitions
/// exercise the real strict-zip profile parser rather than a
/// hand-written verdict.  Debug is enough: the caps make an optimized
/// build irrelevant here.
///
/// # Errors
///
/// If the verifier does not build, if the fixture pair cannot be read,
/// or if either integrity assertion fails.
pub fn setup(registry: &Path) -> Result<Setup> {
    step("building the registry verifier (debug)");
    // The shell's `cd ..`: the build runs from the repository root,
    // where the `cabin` workspace is.
    let repo_root = registry.join("..");
    let failure = match Command::new("cargo")
        .args(["build", "-p", "cabinpkg-registry-verify"])
        .current_dir(&repo_root)
        .output()
    {
        Ok(build) if build.status.success() => None,
        Ok(build) => Some(build_diagnostic(&build)),
        // The shell captured the subshell's own diagnostic too (a
        // missing `cargo` reported itself into `$verifier_build`) and
        // failed with the same message.
        Err(error) => Some(error.to_string()),
    };
    if let Some(diagnostic) = failure {
        eprintln!("{diagnostic}");
        bail!("failed to build cabinpkg-registry-verify");
    }
    let verifier_bin = repo_root.join("target/debug/cabin-registry-verify");

    let fixtures = registry.join("tests/fixtures");
    let fixture_archive = fixtures.join(format!("{SCOPE}-{NAME}-{VERSION}.zip"));
    let fixture_metadata = fixtures.join(format!("{SCOPE}-{NAME}-{VERSION}.json"));
    let fixture_zip = read(&fixture_archive)?;
    let fixture_meta = read(&fixture_metadata)?;
    let blob_hash = sha256_hex(&fixture_zip);
    let rev = revision_of(&fixture_zip);
    let work = TempDir::new().context("creating the work directory")?;

    if !contains(&fixture_meta, format!("\"{SCOPE}/{NAME}\"").as_bytes()) {
        bail!("the frozen fixture must carry the scoped name {SCOPE}/{NAME}");
    }
    // Everything below derives the artifact routes from the revision,
    // so a fixture regenerated onto other bytes must fail here rather
    // than turn the route assertions into 404s that still pass.
    if !contains(
        &fixture_meta,
        format!("{SCOPE}-{NAME}-{VERSION}-{rev}.zip").as_bytes(),
    ) {
        bail!("the frozen fixture's source path does not name revision {rev}");
    }

    Ok(Setup {
        publish_path: format!("/api/v1/packages/{SCOPE}/{NAME}/{VERSION}"),
        package_path: format!("/packages/{SCOPE}/{NAME}.json"),
        artifact_path: format!("/artifacts/{SCOPE}/{NAME}/{SCOPE}-{NAME}-{VERSION}-{rev}.zip"),
        work,
        verifier_bin,
        fixture_archive,
        fixture_metadata,
        fixture_zip,
        fixture_meta,
        blob_hash,
        rev,
    })
}

/// `listing_entry <pending-listing> <name> <version> <out>` (L704-715):
/// extract the one admin-listing element the verifier binary consumes
/// (the `PendingVersion` shape: name, version, revision, checksum,
/// `published_at`, metadata).
///
/// # Errors
///
/// If the listing does not parse, carries no such version, or the entry
/// cannot be written.  All three are the node program's `exit 1`, and
/// the shell replaced every one of them with the single message below.
///
/// The `fail` at L714 is *not* one of the plan's §7.1
/// fail-in-substitution sites: all eight call sites (L1091, L1134,
/// L1365, L1614, L1692, L1867, L1925, L1957) are plain commands, never
/// `$( )`, so `exit 1` runs in the script's own shell and aborts the
/// run.  The port's `?`-propagation matches it exactly.
pub fn listing_entry(listing: &[u8], name: &str, version: &str, out: &Path) -> Result<()> {
    entry_bytes(listing, name, version)
        .and_then(|entry| {
            fs::write(out, entry).with_context(|| format!("writing {}", out.display()))
        })
        .with_context(|| format!("the pending listing has no {name}@{version}"))
}

/// `run_verifier <archive> <listing-entry> <out>` (L720-723): run the
/// built binary, writing its JSON verdict to `out`.
///
/// # Errors
///
/// Exit 2 is an operational failure with no verdict, which must abort
/// the smoke run rather than pass silently.
pub fn run_verifier(verifier_bin: &Path, archive: &Path, entry: &Path, out: &Path) -> Result<()> {
    // The shell put the WHOLE invocation - the `>"$3"` redirection
    // included - before `|| fail`, so a failure to create the out
    // file or to spawn the binary reported through the same wording
    // as a non-zero exit.
    let ran = fs::File::create(out).ok().and_then(|verdict| {
        Command::new(verifier_bin)
            .arg(archive)
            .arg(entry)
            .stdout(Stdio::from(verdict))
            .status()
            .ok()
    });
    if ran.is_some_and(|status| status.success()) {
        return Ok(());
    }
    // `$(cat "$3")`: the file the binary just wrote, which an
    // operational failure leaves empty (exit 2 diagnoses itself on
    // stderr, which stays the operator's).
    let written = fs::read_to_string(out).unwrap_or_default();
    bail!(
        "the verifier binary failed operationally on {}: {written}",
        archive.display()
    );
}

/// L725-744: a token buys nothing the anonymous run did not already
/// have, and nothing off the read plane.
///
/// # Errors
///
/// The first failed check, worded as the shell worded it.
pub fn read_plane(smoke: &mut Smoke, setup: &Setup) -> Result<()> {
    smoke.as_publisher();
    step("read routes serve tokened callers identically");
    smoke.check("/config.json", &[200])?;
    if !contains(&smoke.body, br#""auth-required":false"#) {
        bail!("config.json missing auth-required: {}", body(smoke));
    }
    // The api field names the website origin, crates.io-style.
    if !contains(
        &smoke.body,
        format!("\"api\":\"{}\"", smoke.web_origin()).as_bytes(),
    ) {
        bail!("config.json api is not the website origin: {}", body(smoke));
    }
    // 200 only with previously published local data; 404 proves routing.
    smoke.check("/packages/smoke/withdep.json", &[200, 404])?;
    smoke.check(&setup.artifact_path, &[200, 404])?;

    step("a valid token changes nothing off the read plane on the registry host");
    // Neither `uniform_401` carried `curl_args`, so the credential the
    // two calls at L737-738 present is the one passed in as a header -
    // which `as_publisher` above has just spelled out.
    let bearer = smoke.auth.clone();
    let at = Base::Registry;
    uniform_401_with(
        smoke,
        at,
        "GET",
        "/api/v1/packages/smoke/withdep/0.1.0",
        &bearer,
        None,
    )?;
    uniform_401_with(smoke, at, "GET", "/api/v1/user", &bearer, None)?;

    step("the read plane is absent on the website origin");
    smoke.wcheck("/config.json", &[404])?;
    smoke.wcheck("/packages/smoke/withdep.json", &[404])?;
    smoke.wcheck(&setup.artifact_path, &[404])?;
    smoke.wcheck("/healthz", &[404])?;
    Ok(())
}

/// L751-804: mint a session, read the seeded user with it, prove the
/// post-wipe ghost is refused everywhere, and prove the CSRF header
/// pair is enforced.  Returns the minted cookie for the legs that
/// follow.
///
/// # Errors
///
/// The first failed check, worded as the shell worded it.
pub fn session_plane(smoke: &mut Smoke) -> Result<String> {
    // The session cookie is `<payload>.<hmac>` keyed by SESSION_SECRET,
    // which this run pinned above - so a valid session for the seeded
    // user (github id 0, admitted by the pinned ALLOWED_GITHUB_IDS) can
    // be minted without a GitHub round trip.
    let mut session = session_cookie(0, expires_in_an_hour());
    let csrf = csrf_headers();

    step("session reads answer the seeded user");
    session_request(smoke, &session, "GET", "/api/v1/user", 200, &[], None)?;
    smoke.expect_body(r#""github_id":0"#)?;
    smoke.expect_body(r#""login":"smoke""#)?;
    session_request(smoke, &session, "GET", "/api/v1/user/usage", 200, &[], None)?;
    smoke.expect_body(r#""quotas""#)?;
    session_request(
        smoke,
        &session,
        "GET",
        "/api/v1/user/packages",
        200,
        &[],
        None,
    )?;
    smoke.expect_body(r#""packages""#)?;

    step("a valid session whose identity row is gone answers 401 everywhere");
    // The post-wipe ghost: allowlisted id 1 has a validly sealed cookie
    // but no identity row - every endpoint (the token routes included)
    // answers the same 401 as no session, never an empty listing or a
    // 500.  L786-787 swaps it into the one cookie variable the requests
    // read, and L796 restores the real one.
    let real_session = std::mem::replace(&mut session, session_cookie(1, expires_in_an_hour()));
    session_request(smoke, &session, "GET", "/api/v1/user", 401, &[], None)?;
    session_request(
        smoke,
        &session,
        "GET",
        "/api/v1/user/tokens",
        401,
        &[],
        None,
    )?;
    session_request(
        smoke,
        &session,
        "POST",
        "/api/v1/user/tokens",
        401,
        &csrf,
        Some(br#"{"name":"ghost","scopes":[]}"#),
    )?;
    // Logout is the one exception: a validly sealed cookie is always
    // cleared, identity row or not.
    session_request(
        smoke,
        &session,
        "POST",
        "/api/v1/user/logout",
        200,
        &csrf,
        None,
    )?;
    smoke.expect_body(r#""ok":true"#)?;
    session = real_session;

    step("session mutations enforce the csrf header pair");
    // Each half of the pair alone, spelled out as L800-804 spells it.
    let content_type = vec![("Content-Type".to_owned(), "application/json".to_owned())];
    let protection = vec![("X-CSRF-Protection".to_owned(), "1".to_owned())];
    session_request(
        smoke,
        &session,
        "POST",
        "/api/v1/user/tokens",
        403,
        &content_type,
        Some(CREATE_BODY.as_bytes()),
    )?;
    smoke.expect_body("X-CSRF-Protection")?;
    session_request(
        smoke,
        &session,
        "POST",
        "/api/v1/user/tokens",
        403,
        &protection,
        Some(CREATE_BODY.as_bytes()),
    )?;
    Ok(session)
}

/// The pinned `SESSION_SECRET` this run writes into `.dev.vars`.
const SESSION_SECRET: &[u8] = b"smoke-session-secret-not-for-production";

/// L751-754 and L783-785: the sealed cookie for one github id, which
/// the two mints differ only in.
#[must_use]
pub fn session_cookie(github_id: u64, expires_at: u64) -> String {
    let payload = format!("{github_id}:{expires_at}");
    let mac = hmac_sha256_hex(SESSION_SECRET, format!("session:{payload}").as_bytes());
    format!("cabin_session={payload}.{mac}")
}

/// `csrf_headers` (L768): the header pair every session mutation needs.
#[must_use]
pub fn csrf_headers() -> Vec<(String, String)> {
    vec![
        ("Content-Type".to_owned(), "application/json".to_owned()),
        ("X-CSRF-Protection".to_owned(), "1".to_owned()),
    ]
}

/// `session_request <method> <path> <expected status> [curl args...]`
/// (L758-767): the website origin, the cookie, and exactly one expected
/// status.  The body lands in [`Smoke::body`].
///
/// The shell's variadic tail mixed headers and `--data-binary`; they
/// are split here because the request needs them apart.
///
/// # Errors
///
/// If the status is not `expected`, worded as the shell worded it.
pub fn session_request(
    smoke: &mut Smoke,
    cookie: &str,
    method: &str,
    path: &str,
    expected: u16,
    extra: &[(String, String)],
    data: Option<&[u8]>,
) -> Result<()> {
    let url = smoke.url(Base::Web, path);
    let mut headers = vec![("Cookie".to_owned(), cookie.to_owned())];
    headers.extend_from_slice(extra);
    let status = smoke.http(method, &url, &headers, data)?;
    if status != expected {
        bail!(
            "{method} {path} returned {status}, expected {expected} (body: {})",
            body(smoke)
        );
    }
    println!("    {method} {path} -> {status}");
    Ok(())
}

/// `$(($(date +%s) + 3600))`, the expiry both mints seal.
fn expires_in_an_hour() -> u64 {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |since| since.as_secs());
    now + 3600
}

/// HMAC-SHA256 over the 64-byte block (RFC 2104), lowercase hex - what
/// `openssl dgst -sha256 -hmac <secret> | sed 's/^.* //'` printed.  The
/// repository pulls in no MAC crate and this is the only site that
/// needs one.
fn hmac_sha256_hex(key: &[u8], message: &[u8]) -> String {
    const BLOCK: usize = 64;
    let mut padded = [0u8; BLOCK];
    if key.len() > BLOCK {
        padded[..32].copy_from_slice(&Sha256::digest(key));
    } else {
        padded[..key.len()].copy_from_slice(key);
    }
    let mut inner = padded.map(|byte| byte ^ 0x36).to_vec();
    inner.extend_from_slice(message);
    let mut outer = padded.map(|byte| byte ^ 0x5c).to_vec();
    outer.extend_from_slice(&Sha256::digest(&inner));
    sha256_hex(&outer)
}

/// The node program at L705-714, as its output bytes: the six fields in
/// the order the program lists them (`JSON.stringify` follows insertion
/// order, not the listing's), each dropped when the element does not
/// carry it (`undefined` is not serialized), and every other field of
/// the element left out.
fn entry_bytes(listing: &[u8], name: &str, version: &str) -> Result<Vec<u8>> {
    let doc: serde_json::Value = serde_json::from_slice(listing).context("parsing the listing")?;
    let versions = doc
        .get("versions")
        .and_then(serde_json::Value::as_array)
        .context("the listing carries no versions array")?;
    let found = versions
        .iter()
        .find(|entry| {
            entry.get("name").and_then(serde_json::Value::as_str) == Some(name)
                && entry.get("version").and_then(serde_json::Value::as_str) == Some(version)
        })
        .context("no such version")?;
    let mut entry = serde_json::Map::new();
    for field in [
        "name",
        "version",
        "revision",
        "checksum",
        "published_at",
        "metadata",
    ] {
        if let Some(value) = found.get(field) {
            entry.insert(field.to_owned(), value.clone());
        }
    }
    serde_json::to_vec(&serde_json::Value::Object(entry)).context("serializing the entry")
}

/// `$(cat "$body")` inside a `fail` message.
fn body(smoke: &Smoke) -> String {
    String::from_utf8_lossy(&smoke.body).into_owned()
}

/// The shell captured `cargo build` with `2>&1` and printed the capture
/// only on failure.  The two streams are captured apart here, so their
/// interleaving is lost; the content is not.
fn build_diagnostic(build: &Output) -> String {
    let mut merged = build.stdout.clone();
    merged.extend_from_slice(&build.stderr);
    // `$( )` strips every trailing newline; `printf '%s\n'` adds one.
    String::from_utf8_lossy(&merged)
        .trim_end_matches('\n')
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// printf 'session:0:1234567890' |
    ///   openssl dgst -sha256 -hmac smoke-session-secret-not-for-production
    #[test]
    fn the_session_mac_matches_openssl() {
        assert_eq!(
            hmac_sha256_hex(SESSION_SECRET, b"session:0:1234567890"),
            "35b8dbb6d3040e8e836b068716fa9888fe330bed49894e300eb5281d6b21d7d2"
        );
        assert_eq!(
            session_cookie(0, 1_234_567_890),
            "cabin_session=0:1234567890.\
             35b8dbb6d3040e8e836b068716fa9888fe330bed49894e300eb5281d6b21d7d2"
        );
        // The ghost mint differs only in the id (L783-785).
        assert_eq!(
            session_cookie(1, 1_234_567_890),
            "cabin_session=1:1234567890.\
             4835c7943c20ee3f6f851ded62d13e306af8656644bf0d81eedac31b06fb73e5"
        );
    }
}
