name: Auto Assign Author

on:
  pull_request:
    types: [ opened ]

jobs:
  auto-assign:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
