name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    name: Coveralls and Codecov
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install required libraries
        run: |
          brew update
          brew install libgit2 fmt poacpm/tap/toml11 poacpm/tap/plog boost
          brew install --HEAD poacpm/tap/clipp poacpm/tap/mitama-cpp-result

      - run: mkdir build

      - name: Build Poac
        run: cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Coverage .. && make install
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Upload coverage to Coveralls
        if: success()
        run: |
          pip3 install cpp-coveralls
          coveralls --gcov-options '\-lp' -t ${COVERALLS_TOKEN}
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
