name: Coverage

on: [push, pull_request]

jobs:
  coveralls:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install libgit2
        run: brew install libgit2
      - name: Install toml11
        run: brew install matken11235/toml11/toml11
      - name: Build and Test
        run: |
          mkdir build && cd build
          cmake -Dpoac_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Coverage ..
          make install
          ctest --output-on-failure --verbose
        env:
          POAC_GITHUB_API_TOKEN: ${{ secrets.POAC_GITHUB_API_TOKEN }}
      - name: Upload coverage
        if: success()
        run: |
          pip3 install cpp-coveralls
          coveralls --gcov-options '\-lp' -t ${COVERALLS_TOKEN}
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

  codecov:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install libgit2
        run: brew install libgit2
      - name: Install toml11
        run: brew install matken11235/toml11/toml11
      - name: Build and Test
        run: |
          mkdir build && cd build
          cmake -Dpoac_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Coverage ..
          make install
          ctest --output-on-failure --verbose
        env:
          POAC_GITHUB_API_TOKEN: ${{ secrets.POAC_GITHUB_API_TOKEN }}
      - name: Upload coverage
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
