name: C++

on:
  push:
    branches: [main]
  pull_request:

env:
  CABIN_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build-and-test:
    name: "build & test (${{ matrix.name }} - ${{ matrix.build }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [dev, release]
        include:
          - name: "Clang 16"
            cxx: clang++-16
            os: ubuntu-24.04
          - name: "Clang 17"
            cxx: clang++-17
            os: ubuntu-24.04
          - name: "Clang 18"
            cxx: clang++-18
            os: ubuntu-24.04
          - name: "Clang 19"
            cxx: clang++-19
            os: ubuntu-24.04
          - name: "Clang 20"
            cxx: clang++-20
            os: ubuntu-24.04
          - name: "GCC 12"
            cxx: g++-12
            os: ubuntu-24.04
          - name: "GCC 13"
            cxx: g++-13
            os: ubuntu-24.04
          - name: "GCC 14"
            cxx: g++-14
            os: ubuntu-24.04
          - name: "Apple Clang - macOS 13"
            cxx: c++
            os: macos-13
          - name: "Apple Clang - macOS 14"
            cxx: c++
            os: macos-14
          - name: "Apple Clang - macOS 15"
            cxx: c++
            os: macos-15
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Clang
        if: matrix.cxx == 'clang++-19' || matrix.cxx == 'clang++-20'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh "${CXX##*-}"

      - name: Setup Ubuntu dependencies
        if: runner.os == 'Linux'
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Setup macOS dependencies
        if: runner.os == 'macOS'
        uses: ./.github/actions/setup-macos-deps

      - name: Setup Sharness
        run: |
          wget https://raw.githubusercontent.com/felipec/sharness/refs/tags/v1.2.1/sharness.sh
          wget https://raw.githubusercontent.com/felipec/sharness/refs/tags/v1.2.1/lib-sharness/functions.sh
          mv sharness.sh tests/
          mkdir tests/lib-sharness
          mv functions.sh tests/lib-sharness/

      - name: Print versions
        run: make versions

      - name: Stage 1 - Build
        run: make BUILD=${{ matrix.build }} -j4

      - name: Stage 1 - Print version
        run: ./build/cabin version --verbose

      - name: Stage 1 - Test
        run: make BUILD=${{ matrix.build }} test -j4

      - name: Stage 1 - Integration Test
        run: find tests -maxdepth 1 -name '[0-9]*.sh' -print0 | xargs -0 -I {} sh -c 'sh {} -v'
        env:
          CABIN_TERM_COLOR: auto

      - name: Stage 2 - Build & Test
        run: |
          ./build/cabin --verbose run ${{ matrix.build == 'release' && '--release' || '' }} test --verbose

      - name: Stage 2 - Print version
        run: ./cabin-out/${{ matrix.build }}/cabin version --verbose

      - name: Stage 2 - Integration Test
        run: find tests -maxdepth 1 -name '[0-9]*.sh' -print0 | xargs -0 -I {} sh -c 'sh {} -v'
        env:
          CABIN: ${{ github.workspace }}/cabin-out/${{ matrix.build }}/cabin
          CABIN_TERM_COLOR: auto

      # - name: Print coverage
      #   if: success() && matrix.coverage == 'on'
      #   run: |
      #     lcov --directory . --capture --output-file coverage.info --gcov-tool "${CC_PATH/gcc/gcov}"
      #     lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
      #     lcov --list coverage.info
      #   env:
      #     CC_PATH: /usr/bin/${{ env.CC }}

  format:
    needs: build-and-test
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-18
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make BUILD=release -j4

      - name: Install clang-format-20
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y clang-format-20

      - name: cabin fmt
        run: ./build/cabin fmt --check --verbose
        env:
          CABIN_FMT: clang-format-20

  lint:
    needs: build-and-test
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-18
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make BUILD=release -j4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.*'

      - name: Install cpplint
        run: pip install cpplint

      - name: Show cpplint version
        run: cpplint --version

      - name: cabin lint
        run: ./build/cabin lint --verbose

  clang-tidy:
    needs: build-and-test
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-18
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make BUILD=release -j4

      - name: Install clang-tidy-20
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y clang-tidy-20

      - name: cabin tidy
        run: ./build/cabin tidy --verbose
        env:
          CABIN_TIDY: clang-tidy-20
