name: C++

on:
  push:
    branches: [main]
  pull_request:

env:
  CABIN_TERM_COLOR: always
  CXX: g++-13

permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make RELEASE=1

      - name: Install clang-tidy
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-tidy-18

      - name: cabin tidy
        run: ./build/cabin tidy --verbose
        env:
          CABIN_TIDY: clang-tidy-18

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make RELEASE=1

      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-format-18

      - name: cabin fmt
        run: ./build/cabin fmt --check --verbose --exclude srcOld --exclude testsOld
        env:
          CABIN_FMT: clang-format-18

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make RELEASE=1

      - name: Install cpplint
        run: sudo apt-get install -y cpplint

      - name: cabin lint
        run: ./build/cabin lint --verbose --exclude srcOld --exclude testsOld
