name: C++

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup clang-tidy
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17
          sudo apt-get install -y clang-tidy-17

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgit2-dev

      - name: Run clang-tidy
        run: make tidy
        env:
          CLANG_TIDY: clang-tidy-17

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Poac & clang-format
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update
          brew install poac clang-format
          echo "$(brew --prefix clang-format)/bin" >> "$GITHUB_PATH"

      - name: Check format
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          poac fmt --check --verbose

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgit2-dev

      - name: Build Poac
        run: make RELEASE=1

      - name: Install cpplint
        run: pip install cpplint

      - name: Run lint
        run: ./build-out/poac lint --verbose --exclude srcOld --exclude testsOld
