name: C++

on:
  push:
    branches: [main]
  pull_request:

env:
  POAC_TERM_COLOR: always

permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Poac
        run: make RELEASE=1

      - name: Install clang-tidy
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17
          sudo apt-get install -y clang-tidy-17

      - name: poac tidy
        run: ./build-out/poac tidy --verbose
        env:
          POAC_TIDY: clang-tidy-17

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Poac
        run: make RELEASE=1

      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17
          sudo apt-get install -y clang-format-17

      - name: poac fmt
        run: ./build-out/poac fmt --verbose
        env:
          POAC_FMT: clang-format-17

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Poac
        run: make RELEASE=1

      - name: Install cpplint
        run: pip install cpplint

      - name: poac lint
        run: ./build-out/poac lint --verbose --exclude srcOld --exclude testsOld
