name: C++

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-tidy:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install openssl ninja boost
          brew install libarchive libgit2 fmt spdlog
          brew install llvm  # for clang-tidy
          echo '/usr/local/opt/llvm/bin' >> "$GITHUB_PATH"

      - name: Run CMake
        run: |
          cmake -B build -G Ninja       \
            -DCPM_USE_LOCAL_PACKAGES=ON \
            -DPOAC_BUILD_TESTING=ON     \
            -DPOAC_CLANG_TIDY=ON        \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build Poac
        run: ninja
        working-directory: build

  clang-format:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - "include"
          - "lib"
          - "src"
          - "tests"
    steps:
      - uses: actions/checkout@v3

      - run: clang-tidy --version

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '15'
          check-path: ${{ matrix.path }}

  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --recursive .
