name: C++

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    env:
      CXX: clang++-14
    steps:
      - uses: actions/checkout@v3

      - name: Install required dependencies
        run: |
          sudo apt-get -qq clean
          sudo apt-get -qq update
          sudo apt-get install -y clang-14 lld-14 ninja-build libssl-dev libboost-all-dev

      - name: Run CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DPOAC_BUILD_TESTING=ON

      - name: Build Poac
        run: ninja
        working-directory: build

  clang-format:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - "include"
          - "lib"
          - "src"
          - "tests"
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '15'
          check-path: ${{ matrix.path }}

  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --recursive .
