name: Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t img .

      - name: Create Docker container
        run: docker create img
