name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: "build & test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
        build_type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install          \
            openssl ninja boost \
            libarchive libgit2 fmt spdlog

      - name: Run CMake
        run: |
          cmake -B build -G Ninja \
            -DPOAC_CLANG_TIDY=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Poac
        run: ninja
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Install optional software for some commands
        run: brew install clang-format

      - name: More test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Show link libraries
        run: otool -L ./poac
        working-directory: build

      - name: Print help
        run: ./poac --help
        working-directory: build

      - name: Test binary
        run: |
          ./poac create hello_world
          cd hello_world
          ../poac run
        working-directory: build
