name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: "build & test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
        build_type: [ Debug, Release ]
        use_local: [ on, off ]
    env:
      CACHE_KEY_PREFIX: v2-${{ github.ref }}-${{ matrix.os }}-${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v3

      - name: Install required libraries
        run: brew install openssl ninja boost

      - name: Install optional libraries
        if: matrix.use_local == 'on'
        run: brew install libarchive libgit2 fmt spdlog

      - name: Restore & Cache CMake build results
        uses: actions/cache@v3.0.3
        with:
          path: build
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('CMakeLists.txt', 'cmake/*.cmake') }}

      - name: Run CMake
        run: |
          cmake                                         \
            -B build                                    \
            -G Ninja                                    \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DPOAC_BUILD_TESTING=ON                     \
            -DCPM_USE_LOCAL_PACKAGES=${{ matrix.use_local }}

      - name: Build Poac
        run: ninja
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Install optional software for some commands
        run: brew install clang-format

      - name: More test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Show link libraries
        run: otool -L ./poac
        working-directory: build

      - name: Print help
        run: ./poac --help
        working-directory: build

      - name: Test binary
        run: |
          ./build/poac create hello_world
          cd hello_world
          ../build/poac run
