name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build-and-test:
    name: "build & test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
        build_type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install          \
            llvm                \
            ninja openssl boost \
            fmt libarchive libgit2 spdlog

      - name: Run CMake
        run: |
          cmake -B build -G Ninja \
            -DPOAC_CLANG_TIDY=OFF \
            -DPOAC_BUILD_TESTING=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        env: # TODO: Make POAC_BUILD_TESTING=ON
          CXX: /usr/local/opt/llvm/bin/clang++

      - name: Build Poac
        run: ninja
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Install optional software for some commands
        run: brew install clang-format

      - name: Test Poac more
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Show linked libraries
        run: otool -L ./poac
        working-directory: build

      - name: Print help
        run: ./poac --help
        working-directory: build

      - name: Test binary
        run: |
          ./poac create hello_world
          cd hello_world
          ../poac run
        working-directory: build

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.59.0

      - name: Test conan dependency
        run: |
          git clone https://github.com/wx257osn2/poac-conan-demo.git
          cd poac-conan-demo
          ../build/poac build
