name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15, macos-11.0 ]
        build_type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install required libraries
        run: |
          brew update
          brew install libgit2 fmt poacpm/tap/toml11 poacpm/tap/plog boost
          brew install --HEAD poacpm/tap/clipp poacpm/tap/mitama-cpp-result

      - run: mkdir build

      - name: Build Poac
        run: cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .. && make
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Print help
        run: ./poac help
        working-directory: build
