name: macOS

on: [push, pull_request]

jobs:
  catalina:
    name: Catalina (10.15)
    runs-on: macOS-latest
    strategy:
      matrix:
        build_type: [Debug] # TODO: Release
    steps:
      - uses: actions/checkout@v1
      - name: Install libgit2 & toml11
        run: brew install libgit2 matken11235/toml11/toml11
      - name: Build and Test
        run: |
          mkdir build && cd build
          cmake -Dpoac_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Coverage ..
          make install
          ctest --output-on-failure --verbose
        env:
          POAC_GITHUB_API_TOKEN: ${{ secrets.POAC_GITHUB_API_TOKEN }}
      - name: Print help
        run: poac help

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Catalina (10.15) (${{ matrix.build_type }})*'
          url: ${{ secrets.SLACK_WEBHOOK }}
          username: 'GitHub Action (${{ github.workflow }})'
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
