name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        build_type: [ Debug, Release ]
    env:
      CACHE_KEY_PREFIX: v2-${{ github.ref }}-${{ matrix.os }}-${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v3

      - name: Install required libraries
        run: brew install openssl ninja boost

      - name: Restore & Cache CMake build results
        uses: actions/cache@v3.0.1
        with:
          path: build
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('CMakeLists.txt', 'cmake/*.cmake') }}

      - run: mkdir -p build

      - name: Build Poac
        run: |
          cmake ..                                      \
            -G Ninja                                    \
            -DPOAC_BUILD_TESTING=ON                     \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          ninja
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Print help
        run: ./poac --help
        working-directory: build
