name: macOS

on: [push, pull_request]

jobs:
  catalina:
    name: Catalina (10.15)
    runs-on: macOS-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: Install libgit2
        run: brew install libgit2
      - name: Install toml11
        run: brew install matken11235/toml11/toml11
      - name: Create bulding directory
        run: mkdir build
      - name: Run CMake build
        run: cd build && cmake -Dpoac_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
      - name: Build
        run: cd build && make install
      - name: Test
        run: cd build && ctest --output-on-failure --verbose
        env:
          POAC_GITHUB_API_TOKEN: ${{ secrets.POAC_GITHUB_API_TOKEN }}
      - name: Print help
        run: poac help
