name: macOS

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build-and-test:
    name: "build & test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12, macos-13]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: First Generation Build
        run: make

      - name: Test the first generation
        run: make test

      - name: Second Generation Build
        run: ./build-out/poac build --verbose

      - name: Test the second generation
        run: ./poac-out/debug/poac test --verbose

      - name: Third Generation Build & Test
        run: ./poac-out/debug/poac --verbose run --release test --verbose --release

      # - name: Test Poac
      #   run: ctest --output-on-failure --verbose
      #   working-directory: build
