name: macOS

on:
  push:
    branches: [main]
  pull_request:

env:
  POAC_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build-and-test:
    name: "build & test"
    runs-on: macos-${{ matrix.osver }}
    strategy:
      fail-fast: false
      matrix:
        osver: [13, 14, 15]
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-macos-deps

      - name: Print versions
        run: make versions

      - name: First Generation Build
        run: make -j4

      - name: Test the first generation
        run: make test -j4

      - name: Second Generation Build
        run: ./build-out/poac build --verbose

      - name: Test the second generation
        run: ./poac-out/debug/poac test --verbose

      - name: Third Generation Build & Test
        run: ./poac-out/debug/poac --verbose run --release test --verbose

      - name: Print Poac version
        run: ./poac-out/debug/poac version --verbose

      - name: Create a new project with the third generation
        run: ./poac-out/debug/poac new hello_world

      - name: Run the new project
        run: ../poac-out/debug/poac --verbose run
        working-directory: hello_world

      # - name: Test Poac
      #   run: ctest --output-on-failure --verbose
      #   working-directory: build
