name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: "build & test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
        build_type: [ Debug, Release ]
    env:
      CACHE_KEY_PREFIX: v2-${{ github.ref }}-${{ matrix.os }}-${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v3

      - name: Install required libraries
        run: brew install openssl ninja boost

      - name: Restore & Cache CMake build results
        uses: actions/cache@v3.0.3
        with:
          path: build
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('CMakeLists.txt', 'cmake/*.cmake') }}

      - name: Run CMake
        run: |
          cmake                                         \
            -B build                                    \
            -G Ninja                                    \
            -DPOAC_BUILD_TESTING=ON                     \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Poac
        run: ninja
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Install required software to process UI tests
        run: brew install clang-format

      - name: UI Test
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Print help
        run: ./poac --help
        working-directory: build
