name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - uses: uncenter/setup-taplo@v2
        with:
          version: "0.10.0"

      - name: Check Rust formatting
        run: cargo fmt --all --verbose -- --check

      - name: Check TOML formatting
        run: taplo fmt --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: |
          cargo clippy --workspace --all-targets --all-features --locked \
            --verbose -- -D warnings

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo doc --workspace --all-features --no-deps --locked --verbose
        env:
          RUSTDOCFLAGS: -D warnings

  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install Linux build tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc g++ \
            clang-format clang-tidy pkg-config

      - name: Install macOS build tools
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ninja llvm pkg-config
          echo "$(brew --prefix llvm)/bin" >> "$GITHUB_PATH"

      - name: Build
        run: cargo check --workspace --all-targets --locked --verbose

      - name: Run Tests
        run: |
          cargo test --workspace --all-targets --all-features --locked \
            --verbose -- --show-output
        env:
          RUST_BACKTRACE: "1"
